export type Franchise = { id: string; name: string; codes: string[] };

export const NFL_FRANCHISES: Franchise[] = [
  { id: "ARI", name: "Arizona Cardinals", codes: ["ARI"] },
  { id: "ATL", name: "Atlanta Falcons", codes: ["ATL"] },
  { id: "BAL", name: "Baltimore Ravens", codes: ["BAL"] },
  { id: "BUF", name: "Buffalo Bills", codes: ["BUF"] },
  { id: "CAR", name: "Carolina Panthers", codes: ["CAR"] },
  { id: "CHI", name: "Chicago Bears", codes: ["CHI"] },
  { id: "CIN", name: "Cincinnati Bengals", codes: ["CIN"] },
  { id: "CLE", name: "Cleveland Browns", codes: ["CLE"] },
  { id: "DAL", name: "Dallas Cowboys", codes: ["DAL"] },
  { id: "DEN", name: "Denver Broncos", codes: ["DEN"] },
  { id: "DET", name: "Detroit Lions", codes: ["DET"] },
  { id: "GB", name: "Green Bay Packers", codes: ["GB"] },
  { id: "HOU", name: "Houston Texans", codes: ["HOU"] },
  { id: "IND", name: "Indianapolis Colts", codes: ["IND"] },
  { id: "JAX", name: "Jacksonville Jaguars", codes: ["JAX"] },
  { id: "KC", name: "Kansas City Chiefs", codes: ["KC"] },
  { id: "LAC", name: "Los Angeles Chargers", codes: ["LAC", "SD"] },
  { id: "LAR", name: "Los Angeles Rams", codes: ["LAR", "STL"] },
  { id: "LV", name: "Las Vegas Raiders", codes: ["LV", "OAK", "RAI"] },
  { id: "MIA", name: "Miami Dolphins", codes: ["MIA"] },
  { id: "MIN", name: "Minnesota Vikings", codes: ["MIN"] },
  { id: "NE", name: "New England Patriots", codes: ["NE"] },
  { id: "NO", name: "New Orleans Saints", codes: ["NO"] },
  { id: "NYG", name: "New York Giants", codes: ["NYG"] },
  { id: "PHI", name: "Philadelphia Eagles", codes: ["PHI"] },
  { id: "PIT", name: "Pittsburgh Steelers", codes: ["PIT"] },
  { id: "SEA", name: "Seattle Seahawks", codes: ["SEA"] },
  { id: "SF", name: "San Francisco 49ers", codes: ["SF"] },
  { id: "TB", name: "Tampa Bay Buccaneers", codes: ["TB"] },
  { id: "TEN", name: "Tennessee Titans", codes: ["TEN"] },
  { id: "WAS", name: "Washington Commanders", codes: ["WAS"] },
  { id: "NYJ", name: "New York Jets", codes: ["NYJ"] },
];

/** Extra franchises a player actually suited up for (beyond the primary `team` field). */
export const EXTRA_TEAMS: Record<string, string[]> = {
  brady: ["NE", "TB"],
  moss: ["MIN", "OAK", "NE", "TEN", "SF"],
  to: ["SF", "PHI", "DAL", "BUF", "CIN"],
  fitz: ["ARI"],
  adams: ["GB", "LV", "NYJ"],
  hopkins: ["HOU", "ARI", "TEN"],
  ab: ["PIT", "NE", "TB"],
  obj: ["NYG", "CLE", "LAR", "BAL", "MIA"],
  diggs: ["MIN", "BUF", "HOU"],
  cmc: ["CAR", "SF"],
  saquon: ["NYG", "PHI"],
  ap: ["MIN", "NO", "ARI", "WAS", "TEN"],
  henry: ["TEN", "BAL"],
  lynch: ["BUF", "SEA"],
  cook: ["MIN", "NYJ", "BAL"],
  ekeler: ["LAC", "WAS"],
  bell: ["PIT", "NYJ", "BAL", "TB"],
  vick: ["ATL", "PHI", "NYJ", "PIT"],
  stafford: ["DET", "LAR"],
  rwilson: ["SEA", "DEN", "NYG"],
  rivers: ["LAC", "IND"],
  luck: ["IND"],
  warner: ["STL", "ARI"],
  gonzalez: ["KC", "ATL"],
  gates: ["LAC"],
  witten: ["DAL", "LV"],
  gronk: ["NE", "TB"],
  kelce: ["KC"],
  graham: ["NO", "SEA", "CHI"],
  ertz: ["PHI", "ARI", "WAS"],
  kittle: ["SF"],
  megatron: ["DET"],
  julio: ["ATL", "TEN", "TB"],
  hill: ["KC", "MIA"],
  kupp: ["LAR", "SEA"],
  dez: ["DAL", "NO", "BAL"],
  wayne: ["IND"],
  faulk: ["IND", "STL"],
  lt: ["LAC", "NYJ"],
  dickerson: ["LAR", "IND", "LAR", "ATL", "OAK"],
  esmith: ["DAL", "ARI"],
  mallen: ["RAI", "KC"],
  dorsett: ["DAL", "DEN"],
  tharris: ["PIT", "SEA"],
  tthomas: ["BUF", "MIA"],
  ejames: ["IND", "ARI", "SEA"],
  cmartin: ["NE", "NYJ"],
  bettis: ["LAR", "PIT"],
  watters: ["SF", "PHI", "SEA"],
  portis: ["DEN", "WAS"],
  ftaylor: ["JAX", "NE"],
  jrice: ["SF", "OAK", "SEA"],
  harrison: ["IND"],
  carter: ["MIN", "MIA"],
  tbrown: ["RAI", "TB"],
  deion: ["ATL", "SF", "DAL", "WAS", "BAL"],
  rwhite: ["PHI", "GB", "CAR"],
  bsmith: ["BUF", "WAS"],
  lott: ["SF", "RAI", "NYJ"],
  rwoodson: ["PIT", "SF", "BAL", "OAK"],
  cwoodson: ["OAK", "GB"],
  pepers: ["CAR", "GB", "CHI"],
  peppers: ["CAR", "GB", "CHI"],
  strahan: ["NYG"],
  vmiller: ["DEN", "LAR", "BUF"],
  kmack: ["OAK", "CHI", "LAC"],
  bailey: ["WAS", "DEN"],
  revis: ["NYJ", "TB", "NE", "KC"],
  seau: ["SD", "MIA", "NE"],
  watt: ["HOU", "ARI"],
  jjwatt: ["HOU", "ARI"],
  adonald: ["LAR"],
  ereed: ["BAL", "HOU", "NYJ"],
  polamalu: ["PIT"],
  urlacher: ["CHI"],
  kuechly: ["CAR"],
  unitas: ["IND"],
  mackey: ["IND"],
  moon: ["TEN", "MIN", "SEA", "KC"],
  campbell: ["TEN", "NO"],
  namath: ["NYJ"],
  favre: ["GB", "NYJ", "MIN"],
  rodgers: ["GB", "NYJ"],
  brees: ["SD", "NO"],
  syoung: ["TB", "SF"],
  montana: ["SF", "KC"],
  pmanning: ["IND", "DEN"],
  elway: ["DEN"],
  marino: ["MIA"],
  ben: ["PIT"],
  jallen: ["BUF"],
  ljackson: ["BAL"],
  burrow: ["CIN"],
  dak: ["DAL"],
  hurts: ["PHI"],
  herbert: ["LAC"],
  mahomes: ["KC"],
  sanders: ["DET"],
  payton: ["CHI"],
  jbrown: ["CLE"],
  sayers: ["CHI"],
  simpson: ["BUF", "SF"],
  tdavis: ["DEN"],
  kamara: ["NO"],
  jacobs: ["LV", "GB"],
  mixon: ["CIN", "HOU"],
  bijan: ["ATL"],
  gibbs: ["DET"],
  jtaylor: ["IND"],
  chase: ["CIN"],
  jj: ["MIN"],
  lamb: ["DAL"],
  ajbrown: ["TEN", "PHI"],
  puka: ["LAR"],
  stbrown: ["DET"],
  nico: ["HOU"],
  andrews: ["BAL"],
  laporta: ["DET"],
  mcbride: ["ARI"],
  waller: ["NYG", "LV", "NYG"],
  olson: ["CHI", "CAR", "SEA"],
  clark: ["IND", "TB", "BAL"],
  christensen: ["RAI"],
  casper: ["OAK", "HOU", "MIN"],
  ditka: ["CHI", "DAL", "PHI"],
  newsome: ["CLE"],
  winslow: ["SD"],
  ssharpe: ["DEN", "GB"],
  ssharpew: ["GB"],
  irvin: ["DAL"],
  reed: ["BUF"],
  lofton: ["GB", "RAI", "BUF", "LAR", "PHI"],
  largent: ["SEA"],
  alworth: ["SD", "DAL"],
  hutson: ["GB"],
  swann: ["PIT"],
  stallworth: ["PIT"],
  warfield: ["CLE", "MIA"],
  hward: ["PIT"],
  bruce: ["STL", "SF"],
  holt: ["STL", "NE", "JAX"],
  ochocinco: ["CIN", "NE", "MIA"],
  ajohnson: ["HOU", "IND", "TEN"],
  ajgreen: ["CIN", "ARI"],
  howielong: ["RAI"],
  olsonm: ["LAR"],
  rdent: ["CHI", "SF", "IND", "PHI"],
  atwater: ["DEN", "NYJ"],
  ham: ["PIT"],
  hendricks: ["IND", "GB", "OAK"],
  sap: ["TB", "OAK"],
  sapp: ["TB", "OAK"],
  lilly: ["DAL"],
  blount: ["PIT"],
  ntl: ["LAR", "CHI", "DET"],
  djones: ["LAR", "SD", "WAS"],
  jgreene: ["PIT"],
  ltaylor: ["NYG"],
  raylewis: ["BAL"],
  butkus: ["CHI"],
  lambert: ["PIT"],
  singletary: ["CHI"],
  dthomas: ["KC"],
  ravens00: ["BAL"],
  bears85: ["CHI"],
  seahawks13: ["SEA"],
  steelers76: ["PIT"],
  bucs02: ["TB"],
  jcharles: ["KC", "DEN", "JAX"],
  cj2k: ["TEN", "NYJ", "ARI"],
  bojackson: ["RAI"],
  salexander: ["SEA", "WAS"],
  pholmes: ["BAL", "KC"],
  tavis: ["DEN"],
  aikman: ["DAL"],
  kelly: ["BUF"],
  staubach: ["DAL"],
  tarkenton: ["MIN", "NYG"],
  bradshaw: ["PIT"],
  fouts: ["SD"],
  nitschke: ["GB"],
  wdavis: ["CLE", "GB"],
  adderley: ["GB", "DAL"],
  wwood: ["GB"],
  cmatthews: ["GB", "LAR"],
  packers66: ["GB"],
  alanpage: ["MIN", "CHI"],
  krause: ["WAS", "MIN"],
  randle: ["MIN", "SEA"],
  vikings69: ["MIN"],
  mgarrett: ["CLE"],
  bwillis: ["CLE"],
  hdixon: ["CLE"],
  gatkins: ["CIN"],
  kriley: ["CIN"],
  tbrackens: ["JAX"],
  jramsey: ["JAX", "LAR", "MIA"],
  ccampbell: ["ARI", "JAX", "BAL"],
  rjackson: ["NO", "SF"],
  smills: ["NO", "ATL", "CAR"],
  cjordan: ["NO"],
  saints09: ["NO"],
  jkearse: ["TEN", "PHI"],
  kbulluck: ["TEN", "NYG"],
  staylor: ["WAS"],
  dmanley: ["WAS"],
  tillman: ["ARI"],
  lwilson: ["ARI"],
  aeneas: ["ARI", "STL"],
  chandlerj: ["NE", "ARI"],
  dansby: ["ARI", "MIA", "CLE"],
  dockett: ["ARI"],
  ppeterson: ["ARI", "MIN"],
  chumprey: ["ATL", "PHI"],
  tnobis: ["ATL"],
  tuggle: ["ATL"],
  jabraham: ["NYJ", "ATL", "ARI"],
  gjarrett: ["ATL"],
  rlawrence: ["ATL"],
  cbennett: ["BUF", "ATL", "IND"],
  smerlas: ["BUF", "SF", "NE"],
  twhite: ["BUF", "LAR"],
  conlan: ["BUF", "STL"],
  mariowill: ["HOU", "BUF", "MIA"],
  awinfield: ["BUF", "MIN"],
  tdavislb: ["CAR", "LAC", "WAS"],
  minter: ["CAR"],
  jnorman: ["CAR", "WAS", "SF"],
  kshort: ["CAR"],
  cmatthewsr: ["CLE", "ATL"],
  jhaden: ["CLE", "PIT"],
  mdperry: ["CLE", "DEN", "KC"],
  jhouston: ["CLE"],
  dward: ["CLE"],
  lparrish: ["CIN", "WAS", "BUF"],
  fulcher: ["CIN", "LAR"],
  krumrie: ["CIN"],
  tspikes: ["CIN", "BUF", "PHI", "SF"],
  cdunlap: ["CIN", "SEA"],
  rwilliamslb: ["CIN"],
  randywhite: ["DAL"],
  howley: ["CHI", "DAL"],
  dwoodson: ["DAL"],
  dware: ["DAL", "DEN"],
  lrjordan: ["DAL"],
  charris: ["DAL"],
  tootall: ["DAL"],
  gradishar: ["DEN"],
  mecklenburg: ["DEN"],
  lwright: ["DEN"],
  pryce: ["DEN", "BAL", "NYJ"],
  broncos77: ["DEN"],
  sfletcher: ["DEN"],
  jschmidt: ["DET"],
  karras: ["DET"],
  lbarney: ["DET"],
  spielman: ["DET", "BUF"],
  porcher: ["DET"],
  suh: ["DET", "MIA", "LAR", "TB"],
  dslay: ["DET", "PHI"],
  hjordan: ["CLE", "GB"],
  lbutler: ["GB"],
  drobinson: ["GB", "WAS"],
  timharris: ["GB", "SF", "PHI"],
  kclark: ["GB"],
  cushing: ["HOU"],
  dryans: ["HOU", "PHI"],
  jjoseph: ["CIN", "HOU", "TEN"],
  mercilus: ["HOU", "GB"],
  kjackson: ["HOU", "DEN"],
  gmarchetti: ["IND"],
  freeney: ["IND", "SD", "ARI", "ATL", "SEA", "DET"],
  rmathis: ["IND"],
  bsanders: ["IND"],
  dleonard: ["IND", "PHI"],
  abethea: ["IND", "SF", "ARI", "NYG"],
  telvin: ["JAX"],
  posluszny: ["BUF", "JAX"],
  mstroud: ["JAX", "BUF"],
  jallenjax: ["JAX"],
  jaguars17: ["JAX"],
  dsmithlb: ["JAX", "BAL"],
  wlanier: ["KC"],
  bbell: ["KC"],
  ethomas: ["KC"],
  neilsmith: ["KC", "DEN", "SD"],
  jhoustonkc: ["KC", "IND", "BAL", "CAR"],
  eberry: ["KC"],
  loneal: ["SD", "STL"],
  jbosa: ["LAC"],
  cromartie: ["SD", "NYJ", "ARI", "IND"],
  jammer: ["SD", "DEN"],
  wlowe: ["SD"],
  mingram: ["LAC", "PIT", "MIA", "KC"],
  jtayloridp: ["MIA", "WAS", "NYJ"],
  zthomas: ["MIA", "DAL"],
  buoniconti: ["NE", "MIA"],
  jscott: ["MIA", "WAS"],
  cwake: ["MIA", "TEN"],
  xhoward: ["MIA"],
  dolphins72: ["MIA"],
  celler: ["MIN", "SEA"],
  jmarshall: ["MIN"],
  doleman: ["MIN", "ATL", "SF"],
  jbrowner: ["MIN", "TB"],
  hsmith: ["MIN"],
  greenway: ["MIN"],
  tylaw: ["NE", "NYJ", "KC", "DEN"],
  bruschi: ["NE"],
  mcginest: ["NE", "CLE"],
  seymour: ["NE", "OAK"],
  wilfork: ["NE", "HOU"],
  milloy: ["NE", "BUF", "ATL", "SEA"],
  rharrison: ["SD", "NE"],
  patriots03: ["NE"],
  vrabel: ["PIT", "NE", "KC"],
  swilling: ["NO", "DET", "OAK"],
  vjohnson: ["NO"],
  dsharper: ["GB", "MIN", "NO"],
  mlattimore: ["NO", "WAS"],
  lglover: ["NO", "DAL", "STL"],
  dwaymer: ["NO", "SF", "LAR"],
  hcarson: ["NYG"],
  tunnell: ["NYG", "GB"],
  cbanks: ["NYG", "WAS", "CLE"],
  jpp: ["NYG", "TB", "BAL", "MIA"],
  giants86: ["NYG"],
  shuff: ["NYG", "WAS"],
  jtuck: ["NYG", "OAK"],
  dawkins: ["PHI", "DEN"],
  bednarik: ["PHI"],
  trotter: ["PHI", "WAS"],
  eallen: ["PHI", "NO", "OAK"],
  fcox: ["PHI"],
  sjoyner: ["PHI", "ARI", "GB", "DEN"],
  rsherman: ["SEA", "SF"],
  ethomass: ["SEA", "BAL"],
  keasley: ["SEA"],
  ckenney: ["SEA"],
  bwagner: ["SEA", "LAR", "WAS"],
  jacobgreen: ["SEA"],
  kchancellor: ["SEA"],
  chaley: ["SF", "DAL"],
  pwillis: ["SF"],
  nbowman: ["SF", "OAK"],
  jjohnsondb: ["SF"],
  nbosa: ["SF"],
  fwarner: ["SF"],
  dbrooks: ["TB"],
  selmon: ["TB"],
  jlynchdb: ["TB", "DEN"],
  rbarber: ["TB"],
  srice: ["ARI", "TB"],
  ldavid: ["TB"],
  ebethea: ["TEN"],
  rchildress: ["TEN", "DAL"],
  bbishop: ["TEN", "PHI"],
  srolle: ["TEN", "BAL"],
  jcasey: ["TEN", "DEN"],
  cfinnegan: ["TEN", "STL", "MIA", "CAR"],
  dgreen: ["WAS"],
  hanburger: ["WAS"],
  lfletcher: ["STL", "BUF", "WAS"],
  rkerrigan: ["WAS", "PHI"],
  mcoleman: ["WAS"],
  klecko: ["NYJ"],
  gastineau: ["NYJ"],
  molewis: ["NYJ"],
  dharris: ["NYJ", "NE"],
  sellis: ["NYJ", "NE"],
  jets68: ["NYJ"],
  studwell: ["MIN"],
  ekendricks: ["MIN", "LAC", "DAL"],
  kjwright: ["SEA", "LV"],
  chadbrownlb: ["PIT", "SEA", "NE"],
  gbingham: ["TEN"],
  zbrownlb: ["TEN", "BUF", "WAS", "PHI"],
  ctillman: ["CHI", "CAR"],
  gfencik: ["CHI"],
  rashean: ["JAX", "DET"],
  cardinals08: ["ARI"],
  falcons77: ["ATL"],
  bills90: ["BUF"],
  panthers15: ["CAR"],
  bengals81: ["CIN"],
  browns64: ["CLE"],
  cowboys77: ["DAL"],
  lions57: ["DET"],
  texans11: ["HOU"],
  colts06: ["IND"],
  chiefs69: ["KC"],
  chargers06: ["LAC", "SD"],
  rams67: ["LAR", "STL"],
  raiders76: ["OAK", "LV", "RAI"],
  eagles91: ["PHI"],
  niners84: ["SF"],
  titans00: ["TEN"],
  washington91: ["WAS"],
  cardinals47: ["ARI"],
  cardinals15: ["ARI"],
  falcons98: ["ATL"],
  falcons16: ["ATL"],
  ravens06: ["BAL"],
  ravens12: ["BAL"],
  bills64: ["BUF"],
  bills19: ["BUF"],
  panthers96: ["CAR"],
  panthers03: ["CAR"],
  bears63: ["CHI"],
  bears06: ["CHI"],
  bengals88: ["CIN"],
  bengals21: ["CIN"],
  browns50: ["CLE"],
  browns86: ["CLE"],
  cowboys71: ["DAL"],
  cowboys92: ["DAL"],
  broncos98: ["DEN"],
  broncos15: ["DEN"],
  lions53: ["DET"],
  lions14: ["DET"],
  packers96: ["GB"],
  packers10: ["GB"],
  texans12: ["HOU"],
  texans16: ["HOU"],
  colts58: ["IND"],
  colts70: ["IND"],
  jaguars99: ["JAX"],
  jaguars06: ["JAX"],
  chiefs97: ["KC"],
  chiefs19: ["KC"],
  chargers63: ["LAC", "SD"],
  chargers94: ["LAC", "SD"],
  rams75: ["LAR", "STL"],
  rams99: ["LAR", "STL"],
  raiders67: ["OAK", "LV", "RAI"],
  raiders83: ["OAK", "LV", "RAI"],
  dolphins73: ["MIA"],
  dolphins82: ["MIA"],
  vikings76: ["MIN"],
  vikings17: ["MIN"],
  patriots01: ["NE"],
  patriots14: ["NE"],
  saints91: ["NO"],
  saints18: ["NO"],
  giants90: ["NYG"],
  giants07: ["NYG"],
  jets81: ["NYJ"],
  jets09: ["NYJ"],
  eagles60: ["PHI"],
  eagles17: ["PHI"],
  steelers78: ["PIT"],
  steelers08: ["PIT"],
  seahawks84: ["SEA"],
  seahawks05: ["SEA"],
  niners89: ["SF"],
  niners19: ["SF"],
  bucs79: ["TB"],
  bucs20: ["TB"],
  oilers79: ["TEN"],
  titans08: ["TEN"],
  washington72: ["WAS"],
  washington82: ["WAS"],
};

const COLTS_NOT_RAVENS = new Set(["unitas", "mackey", "gmarchetti", "colts58", "colts70"]);
const OILERS_NOT_TEXANS = new Set(["moon", "campbell", "ebethea", "rchildress", "oilers79"]);

export function franchiseById(id: string) {
  return NFL_FRANCHISES.find((item) => item.id === id) ?? null;
}

export function franchiseName(id: string) {
  return franchiseById(id)?.name ?? id;
}

export function playerTeamCodes(player: { id: string; team: string; teams?: string[] }) {
  if (Array.isArray(player.teams) && player.teams.length) {
    return [...new Set(player.teams)];
  }
  const extra = EXTRA_TEAMS[player.id] ?? [];
  let primary = player.team;
  if (COLTS_NOT_RAVENS.has(player.id)) primary = "IND";
  if (OILERS_NOT_TEXANS.has(player.id)) primary = "TEN";
  return [...new Set([primary, ...extra])];
}

export function franchiseIncludes(franchiseId: string | null | undefined, player: { id: string; team: string }) {
  if (!franchiseId) return true;
  const franchise = franchiseById(franchiseId);
  if (!franchise) return player.team === franchiseId;
  const codes = new Set(franchise.codes);
  return playerTeamCodes(player).some((code) => codes.has(code));
}

export function countFranchisePool(
  players: Array<{ id: string; team: string }>,
  franchiseId: string | null | undefined,
) {
  return players.filter((player) => franchiseIncludes(franchiseId, player)).length;
}

export function countFranchiseIdp(
  players: Array<{ id: string; team: string; position: string }>,
  franchiseId: string | null | undefined,
) {
  return players.filter(
    (player) =>
      ["DL", "LB", "DB", "DST"].includes(player.position) && franchiseIncludes(franchiseId, player),
  ).length;
}
