import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { playerTeamCodes } from "../standalone/franchises.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const offense = JSON.parse(
  fs.readFileSync(path.join(root, "src/lib/offense-players.json"), "utf8"),
);

const STATS = {
  brady: "7× Super Bowl champ · 649 career TD passes",
  montana: "4× Super Bowl champ · 4 Super Bowl MVPs",
  pmanning: "2004: 49 TD passes · 5× NFL MVP",
  mahomes: "3× Super Bowl champ · 50 TD passes in 2018",
  unitas: "47-game TD streak · 3× NFL MVP",
  marino: "1984: 5,084 yards · 48 TD passes",
  elway: "9× Pro Bowl · Super Bowl XXXII/XXXIII champ",
  favre: "297 consecutive starts · 3 straight MVPs (1995–97)",
  rodgers: "2020: 48 TD / 5 INT · 4× NFL MVP",
  brees: "2011: 5,476 passing yards · 5× 5,000-yard seasons",
  syoung: "1994: 70.3% completions · 7× rushing TD season as QB",
  tarkenton: "47,003 passing yards · scrambled for 3,674 rush yards",
  staubach: "Super Bowl VI MVP · 4 Super Bowl trips",
  aikman: "3× Super Bowl champ · 90s Cowboys engine",
  kelly: "4 straight Super Bowls · 13,841 yards in Buffalo",
  moon: "49,325 combined NFL/CFL yards · 1990: 4,689 yards",
  ben: "2× Super Bowl champ · 418 career TD passes",
  warner: "1999: 41 TD passes · Super Bowl XXXIV MVP",
  jallen: "Dual-threat: 200+ rush yards seasons stacked on 30+ TDs",
  ljackson: "2019 MVP: 36 pass TD · 1,206 rush yards",
  burrow: "2021: 34 TD passes · Super Bowl LVI run",
  stafford: "2021 Super Bowl MVP · 500+ TD / INT career grind",
  namath: "Super Bowl III guarantee · 4,007 yards in 1967",
  bradshaw: "4× Super Bowl champ · 1978: 28 TD passes",
  herbert: "2020: 31 TD passes as a rookie",
  hurts: "2022: 13 rush TDs · Super Bowl LIX champ",
  dak: "2016 Offensive Rookie of the Year · 4,500-yard seasons",
  rivers: "63,440 passing yards · 421 TD passes",
  rwilson: "Super Bowl XLVIII champ · 2015: 4,024 yards / 34 TD",
  fouts: "Air Coryell: 3 straight 4,000-yard seasons (1979–81)",
  luck: "2014: 40 TD passes · 2018 comeback player",
  vick: "2006: 1,039 rush yards at QB · 103.1 passer rating",
  sanders: "15,269 rush yards · never a 370-carry season",
  payton: "16,726 rush yards · 1977: 1,852 yards / 16 TD",
  jbrown: "5.2 yards per carry career · 12,312 rush yards in 9 years",
  esmith: "NFL all-time 18,355 rush yards · 164 rush TDs",
  lt: "2006: 31 total TDs · 13,684 rush yards",
  dickerson: "1984: 2,105 rush yards · 13,259 career",
  faulk: "1999: 2,429 yards from scrimmage · 26 total TDs in 2000",
  ap: "2012: 2,097 rush yards · 14,811 career",
  simpson: "1973: 2,003 rush yards in 14 games",
  tdavis: "1998: 2,008 rush yards · Super Bowl XXXII MVP",
  campbell: "1980: 1,934 rush yards · 5.2 YPC that year",
  mallen: "Super Bowl XVIII MVP · 12,243 rush yards",
  dorsett: "12,739 rush yards · 99-yard TD vs. Vikings",
  tharris: "Immaculate Reception · 4 Super Bowl rings",
  tthomas: "1992: 1,487 rush · 626 receiving · Super Bowl XXV",
  ejames: "1999: 1,553 rush yards / 13 TD as a rookie",
  cmartin: "14,101 rush yards · 1,000-yard seasons stacked",
  salexander: "2005: 1,880 rush yards · 27 rush TDs",
  pholmes: "2002: 1,615 rush · 21 rush TDs · 70 receptions",
  sayers: "22 TDs as a rookie (1965) · 4.9 career YPC",
  henry: "2020: 2,027 rush yards · 2024: 1,921 in Baltimore",
  cmc: "2019: 1,387 rush · 1,005 receiving · 19 total TDs",
  saquon: "2018: 2,028 yards from scrimmage as a rookie",
  kamara: "2017: 81/826/5 receiving as a rookie RB",
  cook: "2020: 1,557 rush yards · 7.3 YPC burst seasons",
  jtaylor: "2021: 1,811 rush yards · 18 rush TDs",
  bijan: "2023: 1,163 yards from scrimmage as a rookie",
  gibbs: "2024: 1,412 rush yards · 16 rush TDs",
  bell: "2014: 2,215 yards from scrimmage · 83 catches",
  lynch: "Beast Quake · Super Bowl XLVIII champ",
  jcharles: "2013: 1,287 rush · 693 receiving · 19 total TDs",
  cj2k: "2009: 2,006 rush yards",
  bojackson: "221-yard game vs. Seahawks · 5.4 NFL YPC",
  ekeler: "2022: 107 catches · 18 receiving TDs from the backfield",
  jacobs: "2022: 1,653 rush yards · rushing title",
  mixon: "2021: 1,205 rush · 13 rush TDs",
  bettis: "The Bus: 13,662 rush yards · Super Bowl XL",
  watters: "1994: 1,593 rush · 66 catches in San Francisco",
  portis: "9,923 rush yards · 5.5 YPC as a rookie",
  ftaylor: "11,695 rush yards · 4.6 career YPC",
  jrice: "22,895 receiving yards · 197 TD catches · 1,549 receptions",
  moss: "156 TD catches · 2007: 23 receiving TDs",
  to: "15,934 yards · 153 TD catches",
  harrison: "2002: 143/1,722/11 · 1,102 career catches",
  fitz: "1,432 receptions · 17,492 yards · 11× Pro Bowl",
  megatron: "2012: 1,964 receiving yards · 139.0 passer-rating target",
  julio: "2015: 1,871 yards · 6× 1,400-yard seasons",
  adams: "2020: 115/1,374/18 with Rodgers",
  hill: "2023: 1,799 yards · 10.5 YPC after the catch bursts",
  jj: "2022: 128/1,809/8 · 2024: still a 100-catch pace",
  chase: "2021: 81/1,455/13 as a rookie",
  lamb: "2023: 135/1,749/12",
  hopkins: "2018: 115/1,572/11 · 1,000-yard seasons on three teams",
  ajgreen: "2013: 98/1,426/11",
  carter: "1,101 catches · 130 TD receptions",
  tbrown: "1,094 catches · 14,934 yards · 100 TDs",
  largent: "819 catches · 13,089 yards · never a losing season's fade",
  alworth: "Bambi: 10,266 yards · 18.2 yards per catch",
  hutson: "99 career TDs in the leather-helmet era · 1942: 17 TDs",
  irvin: "11,521 yards · 3 Super Bowl rings · 1995: 1,603 yards",
  reed: "951 catches · 13,095 yards · Bills' Super Bowl years",
  lofton: "14,004 yards · 22.8 YPC burst with the Packers",
  ssharpew: "1992: 108/1,461/13 · career cut short at 27",
  bruce: "15,208 yards · Greatest Show on Turf deep threat",
  holt: "2003: 117/1,696/12 · Rams' GOAT slot of the era",
  ochocinco: "2007: 1,440 yards · 8× 1,000-yard seasons",
  wayne: "1,070 catches · 14,345 yards · Manning's running mate",
  ajohnson: "2012: 1,598 yards · 1,012 career catches",
  dez: "2014: 16 TD catches · 73/1,320/16 that year",
  obj: "2014: 91/1,305/12 as a rookie · The Catch",
  ab: "2014: 129/1,698/13 · 2015: 136/1,834/10",
  diggs: "2020: 127/1,535/8 in Buffalo",
  ajbrown: "2023: 1,456 yards · 14 TDs in Philadelphia",
  puka: "2023: 105/1,486/6 as a rookie",
  stbrown: "2023: 119/1,515/10 · slot machine",
  nico: "2024: 1,000+ yards · 12 TDs breakout",
  kupp: "2021: 145/1,947/16 · Offensive Player of the Year",
  swann: "Super Bowl X MVP · 4 Super Bowl rings",
  warfield: "20.1 yards per catch career · 2 Super Bowl rings",
  stallworth: "Super Bowl XIV: 121 yards · 4 rings in Pittsburgh",
  hward: "1,000 catches · Super Bowl XL MVP",
  gronk: "3 Super Bowl rings · 92 TD catches in 9 years",
  kelce: "2020: 141/1,416/11 · 1,000-yard TE seasons stacked",
  gonzalez: "15,127 yards · 1,325 catches · 111 TD receptions",
  gates: "116 TD catches · 10× Pro Bowl from undrafted",
  witten: "1,228 catches · 13,046 yards · ironman TE",
  ssharpe: "3 Super Bowl rings · 8,438 yards · 62 TDs",
  winslow: "1980: 89/1,290/9 · invented the modern TE",
  newsome: "662 catches · Browns all-time leader for decades",
  ditka: "1961: 56/1,076/12 as a rookie TE",
  mackey: "Super Bowl V champ · 6,186 yards · 38 TDs",
  graham: "2013: 86/1,215/16",
  kittle: "2018: 1,377 yards · 8.5 yards after catch engine",
  andrews: "2021: 107/1,361/9",
  waller: "2020: 107/1,196/9 in Las Vegas",
  laporta: "2023: 86/889/10 as a rookie TE",
  mcbride: "2024: 111/1,146/2 slot-TE volume",
  clark: "2009: 100/1,106/10 with Manning",
  casper: "The Ghost: Super Bowl XI · 17.6 YPC seasons",
  olson: "2014: 84/1,008/6 · 3 straight 1,000-yard TE years",
  ertz: "Super Bowl LII: game-winning TD catch · 2018: 116 catches",
  christensen: "1983: 92/1,247/12 in the Raiders' run",
};

const CORE_DEFENDERS = [
  { id: "ltaylor", name: "Lawrence Taylor", position: "LB", team: "NYG", careerStart: 1981, careerEnd: 1993, targetStd: 9, targetPpr: 16, statLine: "142.0 sacks · 1986 NFL MVP from linebacker" },
  { id: "rwhite", name: "Reggie White", position: "DL", team: "PHI", careerStart: 1985, careerEnd: 2000, targetStd: 14, targetPpr: 21, statLine: "198.0 sacks · Minister of Defense" },
  { id: "jgreene", name: "Joe Greene", position: "DL", team: "PIT", careerStart: 1969, careerEnd: 1981, targetStd: 18, targetPpr: 32, statLine: "Steel Curtain anchor · 4 Super Bowl rings" },
  { id: "deion", name: "Deion Sanders", position: "DB", team: "ATL", careerStart: 1989, careerEnd: 2005, targetStd: 21, targetPpr: 34, statLine: "53 INTs · Prime Time on both sides of the ball" },
  { id: "bsmith", name: "Bruce Smith", position: "DL", team: "BUF", careerStart: 1985, careerEnd: 2003, targetStd: 24, targetPpr: 37, statLine: "NFL-record 200.0 career sacks" },
  { id: "raylewis", name: "Ray Lewis", position: "LB", team: "BAL", careerStart: 1996, careerEnd: 2012, targetStd: 27, targetPpr: 41, statLine: "2,059 tackles · Super Bowl XXXV MVP" },
  { id: "butkus", name: "Dick Butkus", position: "LB", team: "CHI", careerStart: 1965, careerEnd: 1973, targetStd: 29, targetPpr: 44, statLine: "Middle linebacker terror · 8× First-team All-Pro" },
  { id: "lott", name: "Ronnie Lott", position: "DB", team: "SF", careerStart: 1981, careerEnd: 1994, targetStd: 32, targetPpr: 48, statLine: "63 INTs · 4 Super Bowl rings · the pinky" },
  { id: "djones", name: "Deacon Jones", position: "DL", team: "LAR", careerStart: 1961, careerEnd: 1974, targetStd: 34, targetPpr: 51, statLine: "Invented the sack · Fearsome Foursome" },
  { id: "adonald", name: "Aaron Donald", position: "DL", team: "LAR", careerStart: 2014, careerEnd: 2023, targetStd: 37, targetPpr: 54, statLine: "111.0 sacks · 3× Defensive Player of the Year" },
  { id: "bears85", name: "1985 Bears", position: "DST", team: "CHI", careerStart: 1985, careerEnd: 1985, targetStd: 39, targetPpr: 55, statLine: "46 takeaways · Super Bowl XX 46–10 demolition" },
  { id: "jjwatt", name: "J.J. Watt", position: "DL", team: "HOU", careerStart: 2011, careerEnd: 2023, targetStd: 41, targetPpr: 64, statLine: "114.5 sacks · 3× DPOY · 20.5 sacks in 2012" },
  { id: "ereed", name: "Ed Reed", position: "DB", team: "BAL", careerStart: 2002, careerEnd: 2013, targetStd: 43, targetPpr: 66, statLine: "64 INTs · 1,590 INT return yards" },
  { id: "ravens00", name: "2000 Ravens", position: "DST", team: "BAL", careerStart: 2000, careerEnd: 2000, targetStd: 46, targetPpr: 68, statLine: "165 points allowed all year · Super Bowl XXXV" },
  { id: "ntl", name: "Night Train Lane", position: "DB", team: "DET", careerStart: 1952, careerEnd: 1965, targetStd: 49, targetPpr: 71, statLine: "68 INTs · 14 as a rookie in 1952" },
  { id: "lambert", name: "Jack Lambert", position: "LB", team: "PIT", careerStart: 1974, careerEnd: 1984, targetStd: 51, targetPpr: 73, statLine: "Steel Curtain enforcer · 4 Super Bowl rings" },
  { id: "singletary", name: "Mike Singletary", position: "LB", team: "CHI", careerStart: 1981, careerEnd: 1992, targetStd: 54, targetPpr: 77, statLine: "Samurai Mike · 1985 Bears defensive captain" },
  { id: "steelers76", name: "1976 Steelers", position: "DST", team: "PIT", careerStart: 1976, careerEnd: 1976, targetStd: 56, targetPpr: 78, statLine: "Allowed 28 points over the last 9 games" },
  { id: "rwoodson", name: "Rod Woodson", position: "DB", team: "PIT", careerStart: 1987, careerEnd: 2003, targetStd: 58, targetPpr: 83, statLine: "71 INTs · 1,483 INT return yards" },
  { id: "dthomas", name: "Derrick Thomas", position: "LB", team: "KC", careerStart: 1989, careerEnd: 1999, targetStd: 61, targetPpr: 91, statLine: "126.5 sacks · 7-sack game vs. Seattle" },
  { id: "lilly", name: "Bob Lilly", position: "DL", team: "DAL", careerStart: 1961, careerEnd: 1974, targetStd: 64, targetPpr: 93, statLine: "Mr. Cowboy · Doomsday Defense pillar" },
  { id: "blount", name: "Mel Blount", position: "DB", team: "PIT", careerStart: 1970, careerEnd: 1983, targetStd: 67, targetPpr: 99, statLine: "57 INTs · bump-and-run that changed the rules" },
  { id: "cwoodson", name: "Charles Woodson", position: "DB", team: "OAK", careerStart: 1998, careerEnd: 2015, targetStd: 69, targetPpr: 101, statLine: "65 INTs · 2009 Defensive Player of the Year" },
  { id: "urlacher", name: "Brian Urlacher", position: "LB", team: "CHI", careerStart: 2000, careerEnd: 2012, targetStd: 71, targetPpr: 104, statLine: "1,353 tackles · 2005 DPOY" },
  { id: "seahawks13", name: "2013 Seahawks", position: "DST", team: "SEA", careerStart: 2013, careerEnd: 2013, targetStd: 74, targetPpr: 111, statLine: "Legion of Boom · Super Bowl XLVIII 43–8" },
  { id: "seau", name: "Junior Seau", position: "LB", team: "SD", careerStart: 1990, careerEnd: 2009, targetStd: 77, targetPpr: 113, statLine: "1,849 tackles · 12× Pro Bowl" },
  { id: "polamalu", name: "Troy Polamalu", position: "DB", team: "PIT", careerStart: 2003, careerEnd: 2014, targetStd: 79, targetPpr: 116, statLine: "32 INTs · flying-hair pick-sixes · 2 rings" },
  { id: "bailey", name: "Champ Bailey", position: "DB", team: "DEN", careerStart: 1999, careerEnd: 2013, targetStd: 82, targetPpr: 128, statLine: "52 INTs · 12× Pro Bowl shutdown corner" },
  { id: "strahan", name: "Michael Strahan", position: "DL", team: "NYG", careerStart: 1993, careerEnd: 2007, targetStd: 85, targetPpr: 130, statLine: "141.5 sacks · 22.5 in 2001" },
  { id: "peppers", name: "Julius Peppers", position: "DL", team: "CAR", careerStart: 2002, careerEnd: 2018, targetStd: 88, targetPpr: 133, statLine: "159.5 sacks · 11× Pro Bowl" },
  { id: "sapp", name: "Warren Sapp", position: "DL", team: "TB", careerStart: 1995, careerEnd: 2007, targetStd: 91, targetPpr: 135, statLine: "96.5 sacks · Tampa 2 wrecking ball" },
  { id: "vmiller", name: "Von Miller", position: "LB", team: "DEN", careerStart: 2011, careerEnd: 2026, targetStd: 94, targetPpr: 138, statLine: "130+ sacks · Super Bowl 50 MVP" },
  { id: "revis", name: "Darrelle Revis", position: "DB", team: "NYJ", careerStart: 2007, careerEnd: 2017, targetStd: 97, targetPpr: 141, statLine: "Revis Island · 29 INTs · 2009 All-Pro lockdown" },
  { id: "kuechly", name: "Luke Kuechly", position: "LB", team: "CAR", careerStart: 2012, careerEnd: 2019, targetStd: 100, targetPpr: 144, statLine: "1,092 tackles in 8 years · 2013 DPOY" },
  { id: "kmack", name: "Khalil Mack", position: "LB", team: "OAK", careerStart: 2014, careerEnd: 2026, targetStd: 103, targetPpr: 147, statLine: "100+ sacks · 2016 DPOY runner-up seasons" },
  { id: "bucs02", name: "2002 Buccaneers", position: "DST", team: "TB", careerStart: 2002, careerEnd: 2002, targetStd: 106, targetPpr: 150, statLine: "Super Bowl XXXVII · 5 INTs off the Raiders" },
  { id: "ham", name: "Jack Ham", position: "LB", team: "PIT", careerStart: 1971, careerEnd: 1982, targetStd: 109, targetPpr: 153, statLine: "32 INTs from linebacker · 4 Super Bowl rings" },
  { id: "hendricks", name: "Ted Hendricks", position: "LB", team: "OAK", careerStart: 1969, careerEnd: 1983, targetStd: 112, targetPpr: 156, statLine: "The Stork · 4 Super Bowl rings · 26 INTs" },
  { id: "atwater", name: "Steve Atwater", position: "DB", team: "DEN", careerStart: 1989, careerEnd: 1999, targetStd: 115, targetPpr: 159, statLine: "The hit on Christian Okoye · 2 Super Bowl rings" },
  { id: "rdent", name: "Richard Dent", position: "DL", team: "CHI", careerStart: 1983, careerEnd: 1997, targetStd: 118, targetPpr: 162, statLine: "137.5 sacks · Super Bowl XX MVP" },
  { id: "olsenm", name: "Merlin Olsen", position: "DL", team: "LAR", careerStart: 1962, careerEnd: 1976, targetStd: 35, targetPpr: 53, statLine: "Fearsome Foursome · 14 straight Pro Bowls" },
  { id: "howielong", name: "Howie Long", position: "DL", team: "RAI", careerStart: 1981, careerEnd: 1993, targetStd: 90, targetPpr: 134, statLine: "84.0 sacks · 8× Pro Bowl Raider" },
  { id: "nitschke", name: "Ray Nitschke", position: "LB", team: "GB", careerStart: 1958, careerEnd: 1972, targetStd: 44, targetPpr: 62, statLine: "Packers middle linebacker · 5 NFL championships / 2 Super Bowls" },
  { id: "wdavis", name: "Willie Davis", position: "DL", team: "GB", careerStart: 1958, careerEnd: 1969, targetStd: 48, targetPpr: 70, statLine: "Pass-rush pioneer · 5 NFL titles in Green Bay" },
  { id: "adderley", name: "Herb Adderley", position: "DB", team: "GB", careerStart: 1961, careerEnd: 1972, targetStd: 53, targetPpr: 76, statLine: "48 INTs · 5 NFL titles and 3 Super Bowl rings" },
  { id: "wwood", name: "Willie Wood", position: "DB", team: "GB", careerStart: 1960, careerEnd: 1971, targetStd: 87, targetPpr: 125, statLine: "48 INTs · Ice Bowl Packers safety" },
  { id: "cmatthews", name: "Clay Matthews", position: "LB", team: "GB", careerStart: 2009, careerEnd: 2019, targetStd: 92, targetPpr: 136, statLine: "83.5 sacks · Super Bowl XLV" },
  { id: "packers66", name: "1966 Packers", position: "DST", team: "GB", careerStart: 1966, careerEnd: 1966, targetStd: 81, targetPpr: 117, statLine: "First Super Bowl champs · Lombardi's defense" },
  { id: "alanpage", name: "Alan Page", position: "DL", team: "MIN", careerStart: 1967, careerEnd: 1981, targetStd: 42, targetPpr: 60, statLine: "1971 NFL MVP from the defensive line · Purple People Eaters" },
  { id: "krause", name: "Paul Krause", position: "DB", team: "MIN", careerStart: 1964, careerEnd: 1979, targetStd: 72, targetPpr: 102, statLine: "NFL-record 81 career INTs" },
  { id: "randle", name: "John Randle", position: "DL", team: "MIN", careerStart: 1990, careerEnd: 2003, targetStd: 75, targetPpr: 107, statLine: "137.5 sacks · painted-face pass rusher" },
  { id: "vikings69", name: "1969 Vikings", position: "DST", team: "MIN", careerStart: 1969, careerEnd: 1969, targetStd: 84, targetPpr: 120, statLine: "Purple People Eaters · 12–2 juggernaut" },
  { id: "mgarrett", name: "Myles Garrett", position: "DL", team: "CLE", careerStart: 2017, careerEnd: 2026, targetStd: 78, targetPpr: 115, statLine: "Franchise sack king · 2023 DPOY" },
  { id: "bwillis", name: "Bill Willis", position: "DL", team: "CLE", careerStart: 1946, careerEnd: 1953, targetStd: 96, targetPpr: 139, statLine: "AAFC/NFL champion · Browns two-way pioneer" },
  { id: "hdixon", name: "Hanford Dixon", position: "DB", team: "CLE", careerStart: 1981, careerEnd: 1989, targetStd: 119, targetPpr: 163, statLine: "Coined the Dawg Pound · 26 INTs" },
  { id: "gatkins", name: "Geno Atkins", position: "DL", team: "CIN", careerStart: 2010, careerEnd: 2020, targetStd: 98, targetPpr: 142, statLine: "75.5 sacks · interior disruption in Cincinnati" },
  { id: "kriley", name: "Ken Riley", position: "DB", team: "CIN", careerStart: 1969, careerEnd: 1983, targetStd: 101, targetPpr: 145, statLine: "65 INTs · Bengals' all-time pick leader" },
  { id: "tbrackens", name: "Tony Brackens", position: "DL", team: "JAX", careerStart: 1996, careerEnd: 2003, targetStd: 121, targetPpr: 165, statLine: "55.0 sacks · original Jaguar pass rusher" },
  { id: "jramsey", name: "Jalen Ramsey", position: "DB", team: "JAX", careerStart: 2016, careerEnd: 2026, targetStd: 93, targetPpr: 137, statLine: "Lockdown corner · All-Pro in Jacksonville and L.A." },
  { id: "ccampbell", name: "Calais Campbell", position: "DL", team: "JAX", careerStart: 2008, careerEnd: 2026, targetStd: 110, targetPpr: 154, statLine: "100+ sacks · 2017 Jaguars defensive engine" },
  { id: "rjackson", name: "Rickey Jackson", position: "LB", team: "NO", careerStart: 1981, careerEnd: 1995, targetStd: 76, targetPpr: 110, statLine: "128.0 sacks · Dome Patrol" },
  { id: "smills", name: "Sam Mills", position: "LB", team: "NO", careerStart: 1986, careerEnd: 1997, targetStd: 99, targetPpr: 143, statLine: "Dome Patrol · Keep Pounding" },
  { id: "cjordan", name: "Cameron Jordan", position: "DL", team: "NO", careerStart: 2011, careerEnd: 2026, targetStd: 104, targetPpr: 148, statLine: "Saints sack leader · 8× Pro Bowl" },
  { id: "saints09", name: "2009 Saints", position: "DST", team: "NO", careerStart: 2009, careerEnd: 2009, targetStd: 108, targetPpr: 151, statLine: "Super Bowl XLIV · +11 turnover margin" },
  { id: "jkearse", name: "Jevon Kearse", position: "DL", team: "TEN", careerStart: 1999, careerEnd: 2009, targetStd: 89, targetPpr: 132, statLine: "The Freak · 14.5 sacks as a rookie" },
  { id: "kbulluck", name: "Keith Bulluck", position: "LB", team: "TEN", careerStart: 2000, careerEnd: 2010, targetStd: 122, targetPpr: 166, statLine: "Titans tackling machine · 2003 All-Pro" },
  { id: "staylor", name: "Sean Taylor", position: "DB", team: "WAS", careerStart: 2004, careerEnd: 2007, targetStd: 80, targetPpr: 118, statLine: "12 INTs in 4 seasons · feared hitter" },
  { id: "dmanley", name: "Dexter Manley", position: "DL", team: "WAS", careerStart: 1981, careerEnd: 1991, targetStd: 123, targetPpr: 167, statLine: "97.5 unofficial sacks · Super Bowl XXII" },
];

const FRANCHISE_IDP = [
  { id: "tillman", name: "Pat Tillman", position: "DB", team: "ARI", careerStart: 1998, careerEnd: 2001, statLine: "Walked away from the NFL to serve · Cardinals captain" },
  { id: "lwilson", name: "Larry Wilson", position: "DB", team: "ARI", careerStart: 1960, careerEnd: 1972, statLine: "52 INTs · invented the safety blitz" },
  { id: "aeneas", name: "Aeneas Williams", position: "DB", team: "ARI", careerStart: 1991, careerEnd: 2004, statLine: "55 INTs · shutdown corner in Phoenix and St. Louis" },
  { id: "chandlerj", name: "Chandler Jones", position: "DL", team: "ARI", careerStart: 2012, careerEnd: 2023, statLine: "112.0 sacks · 2019 sack champion in Arizona" },
  { id: "dansby", name: "Karlos Dansby", position: "LB", team: "ARI", careerStart: 2004, careerEnd: 2017, statLine: "1,417 tackles · Cardinals tackling machine" },
  { id: "dockett", name: "Darnell Dockett", position: "DL", team: "ARI", careerStart: 2004, careerEnd: 2014, statLine: "40.5 sacks · Super Bowl XLIII interior disruptor" },
  { id: "ppeterson", name: "Patrick Peterson", position: "DB", team: "ARI", careerStart: 2011, careerEnd: 2024, statLine: "8× Pro Bowl · 2011 return-TD rookie year" },
  { id: "chumprey", name: "Claude Humphrey", position: "DL", team: "ATL", careerStart: 1968, careerEnd: 1981, statLine: "122.5 unofficial sacks · Falcons pass-rush original" },
  { id: "tnobis", name: "Tommy Nobis", position: "LB", team: "ATL", careerStart: 1966, careerEnd: 1976, statLine: "Mr. Falcon · 1966 NFL Rookie of the Year" },
  { id: "tuggle", name: "Jessie Tuggle", position: "LB", team: "ATL", careerStart: 1987, careerEnd: 2000, statLine: "1,640 tackles · Falcons all-time tackle king" },
  { id: "jabraham", name: "John Abraham", position: "DL", team: "ATL", careerStart: 2000, careerEnd: 2014, statLine: "133.5 sacks · Jets-to-Falcons edge terror" },
  { id: "gjarrett", name: "Grady Jarrett", position: "DL", team: "ATL", careerStart: 2015, careerEnd: 2026, statLine: "Super Bowl LI 3-sack half · Falcons interior staple" },
  { id: "rlawrence", name: "Rolland Lawrence", position: "DB", team: "ATL", careerStart: 1973, careerEnd: 1980, statLine: "39 INTs · Falcons all-time pick leader" },
  { id: "cbennett", name: "Cornelius Bennett", position: "LB", team: "BUF", careerStart: 1987, careerEnd: 2000, statLine: "71.5 sacks · Bills Super Bowl-era wrecking crew" },
  { id: "smerlas", name: "Fred Smerlas", position: "DL", team: "BUF", careerStart: 1979, careerEnd: 1992, statLine: "5× Pro Bowl nose tackle · 1980s Bills identity" },
  { id: "twhite", name: "Tre'Davious White", position: "DB", team: "BUF", careerStart: 2017, careerEnd: 2026, statLine: "2019 All-Pro lockdown · 18 INTs in Buffalo" },
  { id: "conlan", name: "Shane Conlan", position: "LB", team: "BUF", careerStart: 1987, careerEnd: 1995, statLine: "3× Pro Bowl · Super Bowl-run inside linebacker" },
  { id: "mariowill", name: "Mario Williams", position: "DL", team: "HOU", careerStart: 2006, careerEnd: 2016, statLine: "97.5 sacks · No. 1 pick pass rusher in Houston and Buffalo" },
  { id: "awinfield", name: "Antoine Winfield", position: "DB", team: "BUF", careerStart: 1999, careerEnd: 2012, statLine: "27 INTs · tackling safety in Buffalo then Minnesota" },
  { id: "tdavislb", name: "Thomas Davis", position: "LB", team: "CAR", careerStart: 2005, careerEnd: 2019, statLine: "1,110 tackles · Super Bowl 50 captain after three ACLs" },
  { id: "minter", name: "Mike Minter", position: "DB", team: "CAR", careerStart: 1997, careerEnd: 2006, statLine: "Original Panther safety · 15 INTs, 8 sacks" },
  { id: "jnorman", name: "Josh Norman", position: "DB", team: "CAR", careerStart: 2012, careerEnd: 2023, statLine: "2015 All-Pro · Super Bowl 50 shutdown corner" },
  { id: "kshort", name: "Kawann Short", position: "DL", team: "CAR", careerStart: 2013, careerEnd: 2020, statLine: "55.5 sacks · 2015 All-Pro interior rush" },
  { id: "cmatthewsr", name: "Clay Matthews Sr.", position: "LB", team: "CLE", careerStart: 1978, careerEnd: 1996, statLine: "69.5 sacks · Browns ironman linebacker" },
  { id: "jhaden", name: "Joe Haden", position: "DB", team: "CLE", careerStart: 2010, careerEnd: 2021, statLine: "34 INTs · Dawg Pound then Steelers starter" },
  { id: "mdperry", name: "Michael Dean Perry", position: "DL", team: "CLE", careerStart: 1988, careerEnd: 1997, statLine: "61.0 sacks · 1990s Browns defensive face" },
  { id: "jhouston", name: "Jim Houston", position: "LB", team: "CLE", careerStart: 1960, careerEnd: 1972, statLine: "4× Pro Bowl · Browns championship-era linebacker" },
  { id: "dward", name: "Denzel Ward", position: "DB", team: "CLE", careerStart: 2018, careerEnd: 2026, statLine: "No. 4 pick lockdown · 17+ INTs in Cleveland" },
  { id: "lparrish", name: "Lemar Parrish", position: "DB", team: "CIN", careerStart: 1970, careerEnd: 1982, statLine: "47 INTs · 8× Pro Bowl return man and corner" },
  { id: "fulcher", name: "David Fulcher", position: "DB", team: "CIN", careerStart: 1986, careerEnd: 1993, statLine: "31 INTs · oversized safety in Super Bowl XXIII" },
  { id: "krumrie", name: "Tim Krumrie", position: "DL", team: "CIN", careerStart: 1983, careerEnd: 1994, statLine: "34.5 sacks · Super Bowl XXIII nose tackle" },
  { id: "tspikes", name: "Takeo Spikes", position: "LB", team: "CIN", careerStart: 1998, careerEnd: 2012, statLine: "1,459 tackles · Bengals-to-Bills tackling machine" },
  { id: "cdunlap", name: "Carlos Dunlap", position: "DL", team: "CIN", careerStart: 2010, careerEnd: 2022, statLine: "100.5 sacks · Bengals franchise sack royalty" },
  { id: "rwilliamslb", name: "Reggie Williams", position: "LB", team: "CIN", careerStart: 1976, careerEnd: 1989, statLine: "23.5 sacks · 16 INTs · two Super Bowl trips" },
  { id: "randywhite", name: "Randy White", position: "DL", team: "DAL", careerStart: 1975, careerEnd: 1988, statLine: "The Manster · Super Bowl XII co-MVP" },
  { id: "howley", name: "Chuck Howley", position: "LB", team: "DAL", careerStart: 1958, careerEnd: 1973, statLine: "Only Super Bowl MVP on a losing team · Doomsday" },
  { id: "dwoodson", name: "Darren Woodson", position: "DB", team: "DAL", careerStart: 1992, careerEnd: 2003, statLine: "23 INTs · 3 Super Bowl rings as Dallas's safety" },
  { id: "dware", name: "DeMarcus Ware", position: "LB", team: "DAL", careerStart: 2005, careerEnd: 2016, statLine: "138.5 sacks · Cowboys sack king then Super Bowl 50" },
  { id: "lrjordan", name: "Lee Roy Jordan", position: "LB", team: "DAL", careerStart: 1963, careerEnd: 1976, statLine: "32 INTs · Doomsday middle linebacker" },
  { id: "charris", name: "Cliff Harris", position: "DB", team: "DAL", careerStart: 1970, careerEnd: 1979, statLine: "Captain Crash · 6 Super Bowl trips" },
  { id: "tootall", name: "Ed Too Tall Jones", position: "DL", team: "DAL", careerStart: 1974, careerEnd: 1989, statLine: "57.5 sacks unofficial · 3 Super Bowl rings" },
  { id: "gradishar", name: "Randy Gradishar", position: "LB", team: "DEN", careerStart: 1974, careerEnd: 1983, statLine: "Orange Crush quarterback · 7× Pro Bowl" },
  { id: "mecklenburg", name: "Karl Mecklenburg", position: "LB", team: "DEN", careerStart: 1983, careerEnd: 1994, statLine: "79.0 sacks · 6× Pro Bowl versatile Bronco" },
  { id: "lwright", name: "Louis Wright", position: "DB", team: "DEN", careerStart: 1975, careerEnd: 1986, statLine: "26 INTs · Orange Crush lockdown corner" },
  { id: "pryce", name: "Trevor Pryce", position: "DL", team: "DEN", careerStart: 1997, careerEnd: 2010, statLine: "91.0 sacks · 2 Super Bowl rings in Denver" },
  { id: "broncos77", name: "1977 Broncos", position: "DST", team: "DEN", careerStart: 1977, careerEnd: 1977, statLine: "Orange Crush · first Broncos Super Bowl defense" },
  { id: "sfletcher", name: "Simon Fletcher", position: "LB", team: "DEN", careerStart: 1985, careerEnd: 1995, statLine: "97.5 sacks · Broncos all-time sack leader for years" },
  { id: "jschmidt", name: "Joe Schmidt", position: "LB", team: "DET", careerStart: 1953, careerEnd: 1965, statLine: "10× Pro Bowl · Lions championship middle linebacker" },
  { id: "karras", name: "Alex Karras", position: "DL", team: "DET", careerStart: 1958, careerEnd: 1970, statLine: "4× Pro Bowl · Fearsome Lions defensive tackle" },
  { id: "lbarney", name: "Lem Barney", position: "DB", team: "DET", careerStart: 1967, careerEnd: 1977, statLine: "56 INTs · 7× Pro Bowl Lions corner" },
  { id: "spielman", name: "Chris Spielman", position: "LB", team: "DET", careerStart: 1988, careerEnd: 1997, statLine: "1,294 tackles · 4× Pro Bowl Lions leader" },
  { id: "porcher", name: "Robert Porcher", position: "DL", team: "DET", careerStart: 1992, careerEnd: 2004, statLine: "95.5 sacks · Lions franchise sack king" },
  { id: "suh", name: "Ndamukong Suh", position: "DL", team: "DET", careerStart: 2010, careerEnd: 2022, statLine: "71.5 sacks · 2010 DROY interior wrecking ball" },
  { id: "dslay", name: "Darius Slay", position: "DB", team: "DET", careerStart: 2013, careerEnd: 2026, statLine: "27 INTs · Big Play Slay in Detroit and Philly" },
  { id: "hjordan", name: "Henry Jordan", position: "DL", team: "GB", careerStart: 1957, careerEnd: 1969, statLine: "Lombardi-era pass rusher · 7 NFL titles / Super Bowls" },
  { id: "lbutler", name: "LeRoy Butler", position: "DB", team: "GB", careerStart: 1990, careerEnd: 2001, statLine: "38 INTs · invented the Lambeau Leap" },
  { id: "drobinson", name: "Dave Robinson", position: "LB", team: "GB", careerStart: 1963, careerEnd: 1974, statLine: "12 INTs · Ice Bowl outside linebacker" },
  { id: "timharris", name: "Tim Harris", position: "LB", team: "GB", careerStart: 1986, careerEnd: 1995, statLine: "81.0 sacks · 1989 sack-title Packer" },
  { id: "kclark", name: "Kenny Clark", position: "DL", team: "GB", careerStart: 2016, careerEnd: 2026, statLine: "Packers interior anchor · 40+ sacks in Green Bay" },
  { id: "cushing", name: "Brian Cushing", position: "LB", team: "HOU", careerStart: 2009, careerEnd: 2017, statLine: "2009 DROY · Texans defensive captain" },
  { id: "dryans", name: "DeMeco Ryans", position: "LB", team: "HOU", careerStart: 2006, careerEnd: 2015, statLine: "2006 DROY · 727 tackles in Houston and Philly" },
  { id: "jjoseph", name: "Johnathan Joseph", position: "DB", team: "HOU", careerStart: 2006, careerEnd: 2021, statLine: "32 INTs · Texans shutdown corner for a decade" },
  { id: "mercilus", name: "Whitney Mercilus", position: "LB", team: "HOU", careerStart: 2012, careerEnd: 2021, statLine: "54.0 sacks · J.J. Watt's edge partner" },
  { id: "kjackson", name: "Kareem Jackson", position: "DB", team: "HOU", careerStart: 2010, careerEnd: 2024, statLine: "Texans/Broncos starter · 22 INTs" },
  { id: "gmarchetti", name: "Gino Marchetti", position: "DL", team: "IND", careerStart: 1952, careerEnd: 1966, statLine: "Colts defensive end gold standard · 2 NFL titles" },
  { id: "freeney", name: "Dwight Freeney", position: "DL", team: "IND", careerStart: 2002, careerEnd: 2017, statLine: "125.5 sacks · spin-move Hall of Famer" },
  { id: "rmathis", name: "Robert Mathis", position: "DL", team: "IND", careerStart: 2003, careerEnd: 2016, statLine: "123.0 sacks · 2013 sack champion" },
  { id: "bsanders", name: "Bob Sanders", position: "DB", team: "IND", careerStart: 2004, careerEnd: 2011, statLine: "2007 DPOY · Super Bowl XLI hammer" },
  { id: "dleonard", name: "Darius Leonard", position: "LB", team: "IND", careerStart: 2018, careerEnd: 2026, statLine: "The Maniac · 2018 DROY tackling machine" },
  { id: "abethea", name: "Antoine Bethea", position: "DB", team: "IND", careerStart: 2006, careerEnd: 2019, statLine: "25 INTs · Super Bowl XLI starting safety" },
  { id: "telvin", name: "Telvin Smith", position: "LB", team: "JAX", careerStart: 2014, careerEnd: 2018, statLine: "2017 All-Pro · Jaguars rangy tackling machine" },
  { id: "posluszny", name: "Paul Posluszny", position: "LB", team: "JAX", careerStart: 2007, careerEnd: 2017, statLine: "1,141 tackles · Jaguars defensive captain" },
  { id: "mstroud", name: "Marcus Stroud", position: "DL", team: "JAX", careerStart: 2001, careerEnd: 2010, statLine: "3× Pro Bowl · early-2000s Jaguars wall" },
  { id: "jallenjax", name: "Josh Allen", position: "DL", team: "JAX", careerStart: 2019, careerEnd: 2026, statLine: "Jaguars edge rusher · 50+ sacks in Jacksonville" },
  { id: "jaguars17", name: "2017 Jaguars", position: "DST", team: "JAX", careerStart: 2017, careerEnd: 2017, statLine: "AFC title game · league-best points allowed" },
  { id: "dsmithlb", name: "Daryl Smith", position: "LB", team: "JAX", careerStart: 2004, careerEnd: 2016, statLine: "1,087 tackles · original Jaguar then Ravens starter" },
  { id: "wlanier", name: "Willie Lanier", position: "LB", team: "KC", careerStart: 1967, careerEnd: 1977, statLine: "Contact · Super Bowl IV middle linebacker" },
  { id: "bbell", name: "Bobby Bell", position: "LB", team: "KC", careerStart: 1963, careerEnd: 1974, statLine: "9× AFL All-Star · Super Bowl IV outside linebacker" },
  { id: "ethomas", name: "Emmitt Thomas", position: "DB", team: "KC", careerStart: 1966, careerEnd: 1978, statLine: "58 INTs · Chiefs all-time pick leader" },
  { id: "neilsmith", name: "Neil Smith", position: "DL", team: "KC", careerStart: 1988, careerEnd: 2000, statLine: "104.5 sacks · 6× Pro Bowl then Denver rings" },
  { id: "jhoustonkc", name: "Justin Houston", position: "LB", team: "KC", careerStart: 2011, careerEnd: 2023, statLine: "112.0 sacks · 22.0-sack 2014 season" },
  { id: "eberry", name: "Eric Berry", position: "DB", team: "KC", careerStart: 2010, careerEnd: 2018, statLine: "14 INTs · cancer-comeback All-Pro safety" },
  { id: "loneal", name: "Leslie O'Neal", position: "DL", team: "LAC", careerStart: 1986, careerEnd: 1999, statLine: "132.5 sacks · Chargers sack king" },
  { id: "jbosa", name: "Joey Bosa", position: "DL", team: "LAC", careerStart: 2016, careerEnd: 2026, statLine: "70+ sacks · Chargers edge face of the franchise" },
  { id: "cromartie", name: "Antonio Cromartie", position: "DB", team: "LAC", careerStart: 2006, careerEnd: 2016, statLine: "31 INTs · 109-yard pick-six · Chargers then Jets" },
  { id: "jammer", name: "Quentin Jammer", position: "DB", team: "LAC", careerStart: 2002, careerEnd: 2013, statLine: "21 INTs · Chargers ironman corner" },
  { id: "wlowe", name: "Woodrow Lowe", position: "LB", team: "LAC", careerStart: 1976, careerEnd: 1986, statLine: "21 INTs · Air Coryell-era Chargers linebacker" },
  { id: "mingram", name: "Melvin Ingram", position: "DL", team: "LAC", careerStart: 2012, careerEnd: 2022, statLine: "50.5 sacks · 2017 All-Pro Chargers rusher" },
  { id: "jtayloridp", name: "Jason Taylor", position: "DL", team: "MIA", careerStart: 1997, careerEnd: 2011, statLine: "139.5 sacks · 2006 DPOY" },
  { id: "zthomas", name: "Zach Thomas", position: "LB", team: "MIA", careerStart: 1996, careerEnd: 2008, statLine: "1,734 tackles · 7× All-Pro Dolphins leader" },
  { id: "buoniconti", name: "Nick Buoniconti", position: "LB", team: "MIA", careerStart: 1962, careerEnd: 1976, statLine: "No-Name Defense captain · 2 Super Bowl rings" },
  { id: "jscott", name: "Jake Scott", position: "DB", team: "MIA", careerStart: 1970, careerEnd: 1978, statLine: "Super Bowl VII MVP · 49 INTs" },
  { id: "cwake", name: "Cameron Wake", position: "DL", team: "MIA", careerStart: 2009, careerEnd: 2019, statLine: "100.5 sacks · CFL-to-NFL edge star" },
  { id: "xhoward", name: "Xavien Howard", position: "DB", team: "MIA", careerStart: 2016, careerEnd: 2023, statLine: "29 INTs · 2020 pick champion" },
  { id: "dolphins72", name: "1972 Dolphins", position: "DST", team: "MIA", careerStart: 1972, careerEnd: 1972, statLine: "Perfect season · No-Name Defense" },
  { id: "celler", name: "Carl Eller", position: "DL", team: "MIN", careerStart: 1964, careerEnd: 1979, statLine: "Purple People Eaters · 6× First-team All-Pro" },
  { id: "jmarshall", name: "Jim Marshall", position: "DL", team: "MIN", careerStart: 1960, careerEnd: 1979, statLine: "282 consecutive starts · Purple People Eaters ironman" },
  { id: "doleman", name: "Chris Doleman", position: "DL", team: "MIN", careerStart: 1985, careerEnd: 1999, statLine: "150.5 sacks · 8× Pro Bowl" },
  { id: "jbrowner", name: "Joey Browner", position: "DB", team: "MIN", careerStart: 1983, careerEnd: 1992, statLine: "37 INTs · 6× Pro Bowl Vikings safety" },
  { id: "hsmith", name: "Harrison Smith", position: "DB", team: "MIN", careerStart: 2012, careerEnd: 2026, statLine: "35+ INTs · Vikings all-time safety" },
  { id: "greenway", name: "Chad Greenway", position: "LB", team: "MIN", careerStart: 2006, careerEnd: 2016, statLine: "1,100 tackles · Vikings defensive captain" },
  { id: "tylaw", name: "Ty Law", position: "DB", team: "NE", careerStart: 1995, careerEnd: 2009, statLine: "53 INTs · 3 Super Bowl rings · Brady-era lockdown" },
  { id: "bruschi", name: "Tedy Bruschi", position: "LB", team: "NE", careerStart: 1996, careerEnd: 2008, statLine: "3 Super Bowl rings · stroke-comeback captain" },
  { id: "mcginest", name: "Willie McGinest", position: "LB", team: "NE", careerStart: 1994, careerEnd: 2008, statLine: "86.0 sacks · 3 Super Bowl rings" },
  { id: "seymour", name: "Richard Seymour", position: "DL", team: "NE", careerStart: 2001, careerEnd: 2012, statLine: "57.5 sacks · 3 Super Bowl rings · 7× Pro Bowl" },
  { id: "wilfork", name: "Vince Wilfork", position: "DL", team: "NE", careerStart: 2004, careerEnd: 2016, statLine: "2 Super Bowl rings · 5× Pro Bowl nose tackle" },
  { id: "milloy", name: "Lawyer Milloy", position: "DB", team: "NE", careerStart: 1996, careerEnd: 2012, statLine: "25 INTs · Super Bowl XXXVI starting safety" },
  { id: "rharrison", name: "Rodney Harrison", position: "DB", team: "NE", careerStart: 1994, careerEnd: 2008, statLine: "34 INTs · 30.5 sacks · 2 rings in New England" },
  { id: "patriots03", name: "2003 Patriots", position: "DST", team: "NE", careerStart: 2003, careerEnd: 2003, statLine: "Super Bowl XXXVIII · 24 INTs that year" },
  { id: "vrabel", name: "Mike Vrabel", position: "LB", team: "NE", careerStart: 1997, careerEnd: 2010, statLine: "57.0 sacks · 3 Super Bowl rings · goal-line TD specialist" },
  { id: "swilling", name: "Pat Swilling", position: "LB", team: "NO", careerStart: 1986, careerEnd: 1998, statLine: "107.5 sacks · 1991 DPOY · Dome Patrol" },
  { id: "vjohnson", name: "Vaughan Johnson", position: "LB", team: "NO", careerStart: 1986, careerEnd: 1994, statLine: "Dome Patrol inside linebacker · 4× Pro Bowl" },
  { id: "dsharper", name: "Darren Sharper", position: "DB", team: "NO", careerStart: 1997, careerEnd: 2010, statLine: "63 INTs · Packers/Vikings/Saints ballhawk" },
  { id: "mlattimore", name: "Marshon Lattimore", position: "DB", team: "NO", careerStart: 2017, careerEnd: 2026, statLine: "2017 DROY · Saints lockdown corner" },
  { id: "lglover", name: "La'Roi Glover", position: "DL", team: "NO", careerStart: 1996, careerEnd: 2008, statLine: "83.5 sacks · 2000 sack champion in New Orleans" },
  { id: "dwaymer", name: "Dave Waymer", position: "DB", team: "NO", careerStart: 1980, careerEnd: 1992, statLine: "48 INTs · Saints all-time pick leader" },
  { id: "hcarson", name: "Harry Carson", position: "LB", team: "NYG", careerStart: 1976, careerEnd: 1988, statLine: "9× Pro Bowl · Super Bowl XXI captain" },
  { id: "tunnell", name: "Emlen Tunnell", position: "DB", team: "NYG", careerStart: 1948, careerEnd: 1961, statLine: "79 INTs · first Black Giant Hall of Famer" },
  { id: "cbanks", name: "Carl Banks", position: "LB", team: "NYG", careerStart: 1984, careerEnd: 1995, statLine: "39.5 sacks · 2 Super Bowl rings with LT" },
  { id: "jpp", name: "Jason Pierre-Paul", position: "DL", team: "NYG", careerStart: 2010, careerEnd: 2023, statLine: "94.5 sacks · Super Bowl XLVI then Bucs ring" },
  { id: "giants86", name: "1986 Giants", position: "DST", team: "NYG", careerStart: 1986, careerEnd: 1986, statLine: "Super Bowl XXI · LT's MVP defense" },
  { id: "shuff", name: "Sam Huff", position: "LB", team: "NYG", careerStart: 1956, careerEnd: 1969, statLine: "30 INTs · first TV-famous middle linebacker" },
  { id: "jtuck", name: "Justin Tuck", position: "DL", team: "NYG", careerStart: 2005, careerEnd: 2015, statLine: "66.5 sacks · 2 Super Bowl rings" },
  { id: "dawkins", name: "Brian Dawkins", position: "DB", team: "PHI", careerStart: 1996, careerEnd: 2011, statLine: "37 INTs · 26 sacks · Weapon X in Philly" },
  { id: "bednarik", name: "Chuck Bednarik", position: "LB", team: "PHI", careerStart: 1949, careerEnd: 1962, statLine: "Concrete Charlie · last of the 60-minute men" },
  { id: "trotter", name: "Jeremiah Trotter", position: "LB", team: "PHI", careerStart: 1998, careerEnd: 2009, statLine: "4× Pro Bowl · Eagles middle-linebacker identity" },
  { id: "eallen", name: "Eric Allen", position: "DB", team: "PHI", careerStart: 1988, careerEnd: 2001, statLine: "54 INTs · 6× Pro Bowl Eagles corner" },
  { id: "fcox", name: "Fletcher Cox", position: "DL", team: "PHI", careerStart: 2012, careerEnd: 2023, statLine: "70.0 sacks · Super Bowl LII interior star" },
  { id: "sjoyner", name: "Seth Joyner", position: "LB", team: "PHI", careerStart: 1986, careerEnd: 1998, statLine: "52.0 sacks · Buddy Ryan Eagles enforcer" },
  { id: "rsherman", name: "Richard Sherman", position: "DB", team: "SEA", careerStart: 2011, careerEnd: 2021, statLine: "37 INTs · Legion of Boom lockdown" },
  { id: "ethomass", name: "Earl Thomas", position: "DB", team: "SEA", careerStart: 2010, careerEnd: 2019, statLine: "32 INTs · Legion of Boom center fielder" },
  { id: "keasley", name: "Kenny Easley", position: "DB", team: "SEA", careerStart: 1981, careerEnd: 1987, statLine: "32 INTs · 1984 Seahawks DPOY safety" },
  { id: "ckenney", name: "Cortez Kennedy", position: "DL", team: "SEA", careerStart: 1990, careerEnd: 2000, statLine: "58.0 sacks · 1992 DPOY on a 2–14 team" },
  { id: "bwagner", name: "Bobby Wagner", position: "LB", team: "SEA", careerStart: 2012, careerEnd: 2026, statLine: "1,800+ tackles · Super Bowl XLVIII captain" },
  { id: "jacobgreen", name: "Jacob Green", position: "DL", team: "SEA", careerStart: 1980, careerEnd: 1992, statLine: "115.5 sacks · original Seahawks pass rusher" },
  { id: "kchancellor", name: "Kam Chancellor", position: "DB", team: "SEA", careerStart: 2010, careerEnd: 2017, statLine: "Legion of Boom enforcer · Super Bowl XLVIII" },
  { id: "chaley", name: "Charles Haley", position: "DL", team: "SF", careerStart: 1986, careerEnd: 1999, statLine: "100.5 sacks · 5 Super Bowl rings in SF and Dallas" },
  { id: "pwillis", name: "Patrick Willis", position: "LB", team: "SF", careerStart: 2007, careerEnd: 2014, statLine: "950 tackles · 5× First-team All-Pro" },
  { id: "nbowman", name: "NaVorro Bowman", position: "LB", team: "SF", careerStart: 2010, careerEnd: 2017, statLine: "Harbaugh-era tackling machine · 3× All-Pro" },
  { id: "jjohnsondb", name: "Jimmy Johnson", position: "DB", team: "SF", careerStart: 1961, careerEnd: 1976, statLine: "47 INTs · 49ers shutdown corner Hall of Famer" },
  { id: "nbosa", name: "Nick Bosa", position: "DL", team: "SF", careerStart: 2019, careerEnd: 2026, statLine: "2022 DPOY · Super Bowl LVIII pass rush" },
  { id: "fwarner", name: "Fred Warner", position: "LB", team: "SF", careerStart: 2018, careerEnd: 2026, statLine: "All-Pro coverage linebacker · 49ers defensive quarterback" },
  { id: "dbrooks", name: "Derrick Brooks", position: "LB", team: "TB", careerStart: 1995, careerEnd: 2008, statLine: "1,713 tackles · 2002 DPOY · Super Bowl XXXVII" },
  { id: "selmon", name: "Lee Roy Selmon", position: "DL", team: "TB", careerStart: 1976, careerEnd: 1984, statLine: "78.5 unofficial sacks · original Buccaneer great" },
  { id: "jlynchdb", name: "John Lynch", position: "DB", team: "TB", careerStart: 1993, careerEnd: 2007, statLine: "26 INTs · Tampa 2 then Broncos Pro Bowls" },
  { id: "rbarber", name: "Ronde Barber", position: "DB", team: "TB", careerStart: 1997, careerEnd: 2012, statLine: "47 INTs · 28 sacks · Super Bowl XXXVII" },
  { id: "srice", name: "Simeon Rice", position: "DL", team: "TB", careerStart: 1996, careerEnd: 2007, statLine: "122.0 sacks · Super Bowl XXXVII edge rusher" },
  { id: "ldavid", name: "Lavonte David", position: "LB", team: "TB", careerStart: 2012, careerEnd: 2026, statLine: "1,500+ tackles · Bucs coverage linebacker" },
  { id: "ebethea", name: "Elvin Bethea", position: "DL", team: "TEN", careerStart: 1968, careerEnd: 1983, statLine: "105.0 unofficial sacks · Oilers Hall of Fame rusher" },
  { id: "rchildress", name: "Ray Childress", position: "DL", team: "TEN", careerStart: 1985, careerEnd: 1996, statLine: "76.5 sacks · Oilers/Titans defensive face" },
  { id: "bbishop", name: "Blaine Bishop", position: "DB", team: "TEN", careerStart: 1993, careerEnd: 2002, statLine: "5× Pro Bowl · Oilers/Titans hitting safety" },
  { id: "srolle", name: "Samari Rolle", position: "DB", team: "TEN", careerStart: 1998, careerEnd: 2008, statLine: "31 INTs · Titans then Ravens starter" },
  { id: "jcasey", name: "Jurrell Casey", position: "DL", team: "TEN", careerStart: 2011, careerEnd: 2020, statLine: "51.0 sacks · 5× Pro Bowl Titans tackle" },
  { id: "cfinnegan", name: "Cortland Finnegan", position: "DB", team: "TEN", careerStart: 2006, careerEnd: 2015, statLine: "18 INTs · 2008 All-Pro Titans corner" },
  { id: "dgreen", name: "Darrell Green", position: "DB", team: "WAS", careerStart: 1983, careerEnd: 2002, statLine: "54 INTs · 20 seasons of lockdown speed" },
  { id: "hanburger", name: "Chris Hanburger", position: "LB", team: "WAS", careerStart: 1965, careerEnd: 1978, statLine: "9× Pro Bowl · Over-the-Hill Gang captain" },
  { id: "lfletcher", name: "London Fletcher", position: "LB", team: "WAS", careerStart: 1998, careerEnd: 2013, statLine: "2,039 tackles · ironman in St. Louis, Buffalo, Washington" },
  { id: "rkerrigan", name: "Ryan Kerrigan", position: "LB", team: "WAS", careerStart: 2011, careerEnd: 2021, statLine: "95.5 sacks · Washington franchise sack king" },
  { id: "mcoleman", name: "Monte Coleman", position: "LB", team: "WAS", careerStart: 1979, careerEnd: 1994, statLine: "56.5 sacks unofficial · 3 Super Bowl rings" },
  { id: "klecko", name: "Joe Klecko", position: "DL", team: "NYJ", careerStart: 1977, careerEnd: 1988, statLine: "New York Sack Exchange · Pro Bowl at three spots" },
  { id: "gastineau", name: "Mark Gastineau", position: "DL", team: "NYJ", careerStart: 1979, careerEnd: 1988, statLine: "74.0 sacks · 1983 unofficial 19-sack year" },
  { id: "molewis", name: "Mo Lewis", position: "LB", team: "NYJ", careerStart: 1991, careerEnd: 2003, statLine: "1,226 tackles · hit that changed the Patriots' QB" },
  { id: "dharris", name: "David Harris", position: "LB", team: "NYJ", careerStart: 2007, careerEnd: 2017, statLine: "1,089 tackles · Jets defensive captain" },
  { id: "sellis", name: "Shaun Ellis", position: "DL", team: "NYJ", careerStart: 2000, careerEnd: 2012, statLine: "73.5 sacks · Jets edge staple of the 2000s" },
  { id: "jets68", name: "1968 Jets", position: "DST", team: "NYJ", careerStart: 1968, careerEnd: 1968, statLine: "Super Bowl III · Joe Namath's guarantee defense" },
  { id: "studwell", name: "Scott Studwell", position: "LB", team: "MIN", careerStart: 1977, careerEnd: 1990, statLine: "1,981 unofficial tackles · Vikings linebacker ironman" },
  { id: "ekendricks", name: "Eric Kendricks", position: "LB", team: "MIN", careerStart: 2015, careerEnd: 2026, statLine: "2019 All-Pro · Vikings coverage linebacker" },
  { id: "kjwright", name: "K.J. Wright", position: "LB", team: "SEA", careerStart: 2011, careerEnd: 2021, statLine: "Legion of Boom linebacker · Super Bowl XLVIII" },
  { id: "chadbrownlb", name: "Chad Brown", position: "LB", team: "SEA", careerStart: 1993, careerEnd: 2007, statLine: "79.0 sacks · Steelers then Seahawks Pro Bowler" },
  { id: "gbingham", name: "Gregg Bingham", position: "LB", team: "TEN", careerStart: 1973, careerEnd: 1984, statLine: "Oilers tackling machine · 1970s Houston defense" },
  { id: "zbrownlb", name: "Zach Brown", position: "LB", team: "TEN", careerStart: 2012, careerEnd: 2019, statLine: "2016 All-Pro tackler · Titans then Redskins" },
  { id: "ctillman", name: "Charles Tillman", position: "DB", team: "CHI", careerStart: 2003, careerEnd: 2015, statLine: "38 INTs · Peanut punch specialist" },
  { id: "gfencik", name: "Gary Fencik", position: "DB", team: "CHI", careerStart: 1976, careerEnd: 1987, statLine: "38 INTs · 1985 Bears safety captain" },
  { id: "rashean", name: "Rashean Mathis", position: "DB", team: "JAX", careerStart: 2003, careerEnd: 2015, statLine: "32 INTs · Jaguars all-time pick leader" },
  { id: "cardinals08", name: "2008 Cardinals", position: "DST", team: "ARI", careerStart: 2008, careerEnd: 2008, statLine: "Super Bowl XLIII · first NFC title in the desert" },
  { id: "falcons77", name: "1977 Falcons", position: "DST", team: "ATL", careerStart: 1977, careerEnd: 1977, statLine: "Grits Blitz · 129 points allowed, 9.2 per game" },
  { id: "bills90", name: "1990 Bills", position: "DST", team: "BUF", careerStart: 1990, careerEnd: 1990, statLine: "Super Bowl XXV run · Bruce Smith’s Bills D" },
  { id: "panthers15", name: "2015 Panthers", position: "DST", team: "CAR", careerStart: 2015, careerEnd: 2015, statLine: "15–1 · Super Bowl 50 · 24 takeaways" },
  { id: "bengals81", name: "1981 Bengals", position: "DST", team: "CIN", careerStart: 1981, careerEnd: 1981, statLine: "Super Bowl XVI · Freezer Bowl AFC champs" },
  { id: "browns64", name: "1964 Browns", position: "DST", team: "CLE", careerStart: 1964, careerEnd: 1964, statLine: "Last Cleveland title · shut down the Colts in the NFL Championship" },
  { id: "cowboys77", name: "1977 Cowboys", position: "DST", team: "DAL", careerStart: 1977, careerEnd: 1977, statLine: "Doomsday Defense · Super Bowl XII 27–10" },
  { id: "lions57", name: "1957 Lions", position: "DST", team: "DET", careerStart: 1957, careerEnd: 1957, statLine: "NFL champions · last Lions title defense" },
  { id: "texans11", name: "2011 Texans", position: "DST", team: "HOU", careerStart: 2011, careerEnd: 2011, statLine: "Watt’s first playoff D · AFC South champs" },
  { id: "colts06", name: "2006 Colts", position: "DST", team: "IND", careerStart: 2006, careerEnd: 2006, statLine: "Super Bowl XLI · Bob Sanders DPOY defense" },
  { id: "chiefs69", name: "1969 Chiefs", position: "DST", team: "KC", careerStart: 1969, careerEnd: 1969, statLine: "Super Bowl IV · stacked AFL championship D" },
  { id: "chargers06", name: "2006 Chargers", position: "DST", team: "LAC", careerStart: 2006, careerEnd: 2006, statLine: "14–2 · Merriman/Phillips Lights Out rush" },
  { id: "rams67", name: "1967 Rams", position: "DST", team: "LAR", careerStart: 1967, careerEnd: 1967, statLine: "Fearsome Foursome · 11–1–2 Coastal champs" },
  { id: "raiders76", name: "1976 Raiders", position: "DST", team: "OAK", careerStart: 1976, careerEnd: 1976, statLine: "Super Bowl XI · 13–1 Silver and Black D" },
  { id: "eagles91", name: "1991 Eagles", position: "DST", team: "PHI", careerStart: 1991, careerEnd: 1991, statLine: "Buddy Ryan leftover · 48 sacks, 10–6 without McMahon" },
  { id: "niners84", name: "1984 49ers", position: "DST", team: "SF", careerStart: 1984, careerEnd: 1984, statLine: "Super Bowl XIX · 15–1 Montana-era defense" },
  { id: "titans00", name: "2000 Titans", position: "DST", team: "TEN", careerStart: 2000, careerEnd: 2000, statLine: "AFC title game · Kearse/Bulluck Titans D" },
  { id: "washington91", name: "1991 Washington", position: "DST", team: "WAS", careerStart: 1991, careerEnd: 1991, statLine: "Super Bowl XXVI · 14–2 Gibbs championship D" },
  { id: "cardinals47", name: "1947 Cardinals", position: "DST", team: "ARI", careerStart: 1947, careerEnd: 1947, statLine: "NFL champions · last Cardinals title in Chicago" },
  { id: "cardinals15", name: "2015 Cardinals", position: "DST", team: "ARI", careerStart: 2015, careerEnd: 2015, statLine: "13–3 NFC West champs · Peterson/Campbell D" },
  { id: "falcons98", name: "1998 Falcons", position: "DST", team: "ATL", careerStart: 1998, careerEnd: 1998, statLine: "Super Bowl XXXIII · 14–2 Dirty Birds" },
  { id: "falcons16", name: "2016 Falcons", position: "DST", team: "ATL", careerStart: 2016, careerEnd: 2016, statLine: "Super Bowl LI · NFC champions in Atlanta" },
  { id: "ravens06", name: "2006 Ravens", position: "DST", team: "BAL", careerStart: 2006, careerEnd: 2006, statLine: "League-best scoring D · 13–3 Lewis/Reed" },
  { id: "ravens12", name: "2012 Ravens", position: "DST", team: "BAL", careerStart: 2012, careerEnd: 2012, statLine: "Super Bowl XLVII · Suggs/Lewis swan song" },
  { id: "bills64", name: "1964 Bills", position: "DST", team: "BUF", careerStart: 1964, careerEnd: 1964, statLine: "AFL champions · Saban’s Buffalo defense" },
  { id: "bills19", name: "2019 Bills", position: "DST", team: "BUF", careerStart: 2019, careerEnd: 2019, statLine: "Playoff return · White/Milano/Hyde D" },
  { id: "panthers96", name: "1996 Panthers", position: "DST", team: "CAR", careerStart: 1996, careerEnd: 1996, statLine: "NFC title game in year two · Mills/Greene D" },
  { id: "panthers03", name: "2003 Panthers", position: "DST", team: "CAR", careerStart: 2003, careerEnd: 2003, statLine: "Super Bowl XXXVIII · Peppers/Morgan D" },
  { id: "bears63", name: "1963 Bears", position: "DST", team: "CHI", careerStart: 1963, careerEnd: 1963, statLine: "NFL champions · George Halas’s last title D" },
  { id: "bears06", name: "2006 Bears", position: "DST", team: "CHI", careerStart: 2006, careerEnd: 2006, statLine: "Super Bowl XLI · Urlacher/Briggs/Tillman" },
  { id: "bengals88", name: "1988 Bengals", position: "DST", team: "CIN", careerStart: 1988, careerEnd: 1988, statLine: "Super Bowl XXIII · Fulcher/Krumrie D" },
  { id: "bengals21", name: "2021 Bengals", position: "DST", team: "CIN", careerStart: 2021, careerEnd: 2021, statLine: "Super Bowl LVI · Hendrickson/Bates D" },
  { id: "browns50", name: "1950 Browns", position: "DST", team: "CLE", careerStart: 1950, careerEnd: 1950, statLine: "NFL champions in year one · Graham-era D" },
  { id: "browns86", name: "1986 Browns", position: "DST", team: "CLE", careerStart: 1986, careerEnd: 1986, statLine: "AFC title · Dawg Pound Dixon/Wright D" },
  { id: "cowboys71", name: "1971 Cowboys", position: "DST", team: "DAL", careerStart: 1971, careerEnd: 1971, statLine: "Super Bowl VI · original Doomsday Defense" },
  { id: "cowboys92", name: "1992 Cowboys", position: "DST", team: "DAL", careerStart: 1992, careerEnd: 1992, statLine: "Super Bowl XXVII · Jimmy Johnson’s D" },
  { id: "broncos98", name: "1998 Broncos", position: "DST", team: "DEN", careerStart: 1998, careerEnd: 1998, statLine: "Super Bowl XXXIII · Atwater/Gordon repeat D" },
  { id: "broncos15", name: "2015 Broncos", position: "DST", team: "DEN", careerStart: 2015, careerEnd: 2015, statLine: "Super Bowl 50 · No Fly Zone + Von Miller MVP" },
  { id: "lions53", name: "1953 Lions", position: "DST", team: "DET", careerStart: 1953, careerEnd: 1953, statLine: "NFL champions · Schmidt/Christiansen D" },
  { id: "lions14", name: "2014 Lions", position: "DST", team: "DET", careerStart: 2014, careerEnd: 2014, statLine: "Suh/Fairley/Slay · 11–5 scoring D" },
  { id: "packers96", name: "1996 Packers", position: "DST", team: "GB", careerStart: 1996, careerEnd: 1996, statLine: "Super Bowl XXXI · White/Butler/Woodson D" },
  { id: "packers10", name: "2010 Packers", position: "DST", team: "GB", careerStart: 2010, careerEnd: 2010, statLine: "Super Bowl XLV · Matthews/Woodson/Raji" },
  { id: "texans12", name: "2012 Texans", position: "DST", team: "HOU", careerStart: 2012, careerEnd: 2012, statLine: "Watt 20.5-sack DPOY season · 12–4" },
  { id: "texans16", name: "2016 Texans", position: "DST", team: "HOU", careerStart: 2016, careerEnd: 2016, statLine: "AFC South champs · Watt/Clowney/Mercilus" },
  { id: "colts58", name: "1958 Colts", position: "DST", team: "IND", careerStart: 1958, careerEnd: 1958, statLine: "The Greatest Game · Marchetti championship D" },
  { id: "colts70", name: "1970 Colts", position: "DST", team: "IND", careerStart: 1970, careerEnd: 1970, statLine: "Super Bowl V · Baltimore Colts title D" },
  { id: "jaguars99", name: "1999 Jaguars", position: "DST", team: "JAX", careerStart: 1999, careerEnd: 1999, statLine: "AFC title game · 14–2 Brackens/Stroud D" },
  { id: "jaguars06", name: "2006 Jaguars", position: "DST", team: "JAX", careerStart: 2006, careerEnd: 2006, statLine: "Top-five scoring D · Henderson/Stroud wall" },
  { id: "chiefs97", name: "1997 Chiefs", position: "DST", team: "KC", careerStart: 1997, careerEnd: 1997, statLine: "13–3 AFC West · Thomas/Grier D" },
  { id: "chiefs19", name: "2019 Chiefs", position: "DST", team: "KC", careerStart: 2019, careerEnd: 2019, statLine: "Super Bowl LIV · Chris Jones/Mathieu D" },
  { id: "chargers63", name: "1963 Chargers", position: "DST", team: "LAC", careerStart: 1963, careerEnd: 1963, statLine: "AFL champions · Faison/Lincoln D" },
  { id: "chargers94", name: "1994 Chargers", position: "DST", team: "LAC", careerStart: 1994, careerEnd: 1994, statLine: "Super Bowl XXIX · Seau’s Bolts D" },
  { id: "rams75", name: "1975 Rams", position: "DST", team: "LAR", careerStart: 1975, careerEnd: 1975, statLine: "NFC champs · Youngblood/Olsen Foursome D" },
  { id: "rams99", name: "1999 Rams", position: "DST", team: "LAR", careerStart: 1999, careerEnd: 1999, statLine: "Super Bowl XXXIV · Greatest Show on Turf D" },
  { id: "raiders67", name: "1967 Raiders", position: "DST", team: "OAK", careerStart: 1967, careerEnd: 1967, statLine: "AFL champions · 13–1 Silver and Black" },
  { id: "raiders83", name: "1983 Raiders", position: "DST", team: "OAK", careerStart: 1983, careerEnd: 1983, statLine: "Super Bowl XVIII · Haynes/Alzado/Millen" },
  { id: "dolphins73", name: "1973 Dolphins", position: "DST", team: "MIA", careerStart: 1973, careerEnd: 1973, statLine: "Super Bowl VIII repeat · No-Name Defense" },
  { id: "dolphins82", name: "1982 Dolphins", position: "DST", team: "MIA", careerStart: 1982, careerEnd: 1982, statLine: "Super Bowl XVII · Killer B’s" },
  { id: "vikings76", name: "1976 Vikings", position: "DST", team: "MIN", careerStart: 1976, careerEnd: 1976, statLine: "Super Bowl XI · Purple People Eaters encore" },
  { id: "vikings17", name: "2017 Vikings", position: "DST", team: "MIN", careerStart: 2017, careerEnd: 2017, statLine: "Minneapolis Miracle year · Hunter/Griffen D" },
  { id: "patriots01", name: "2001 Patriots", position: "DST", team: "NE", careerStart: 2001, careerEnd: 2001, statLine: "Super Bowl XXXVI · Bruschi/Law/Milloy" },
  { id: "patriots14", name: "2014 Patriots", position: "DST", team: "NE", careerStart: 2014, careerEnd: 2014, statLine: "Super Bowl XLIX · Butler’s goal-line INT" },
  { id: "saints91", name: "1991 Saints", position: "DST", team: "NO", careerStart: 1991, careerEnd: 1991, statLine: "Dome Patrol peak · 11–5 first division title" },
  { id: "saints18", name: "2018 Saints", position: "DST", team: "NO", careerStart: 2018, careerEnd: 2018, statLine: "13–3 NFC South · Jordan/Lattimore D" },
  { id: "giants90", name: "1990 Giants", position: "DST", team: "NYG", careerStart: 1990, careerEnd: 1990, statLine: "Super Bowl XXV · LT/Banks/Reasons D" },
  { id: "giants07", name: "2007 Giants", position: "DST", team: "NYG", careerStart: 2007, careerEnd: 2007, statLine: "Super Bowl XLII · Strahan/Umenyiora/Tuck" },
  { id: "jets81", name: "1981 Jets", position: "DST", team: "NYJ", careerStart: 1981, careerEnd: 1981, statLine: "New York Sack Exchange · Klecko/Gastineau" },
  { id: "jets09", name: "2009 Jets", position: "DST", team: "NYJ", careerStart: 2009, careerEnd: 2009, statLine: "AFC title game · Revis Island" },
  { id: "eagles60", name: "1960 Eagles", position: "DST", team: "PHI", careerStart: 1960, careerEnd: 1960, statLine: "NFL champions · Bednarik’s last title D" },
  { id: "eagles17", name: "2017 Eagles", position: "DST", team: "PHI", careerStart: 2017, careerEnd: 2017, statLine: "Super Bowl LII · Cox/Graham/Jenkins D" },
  { id: "steelers78", name: "1978 Steelers", position: "DST", team: "PIT", careerStart: 1978, careerEnd: 1978, statLine: "Super Bowl XIII · Steel Curtain title encore" },
  { id: "steelers08", name: "2008 Steelers", position: "DST", team: "PIT", careerStart: 2008, careerEnd: 2008, statLine: "Super Bowl XLIII · Harrison/Polamalu D" },
  { id: "seahawks84", name: "1984 Seahawks", position: "DST", team: "SEA", careerStart: 1984, careerEnd: 1984, statLine: "Easley DPOY · first Seattle division title" },
  { id: "seahawks05", name: "2005 Seahawks", position: "DST", team: "SEA", careerStart: 2005, careerEnd: 2005, statLine: "Super Bowl XL · Alexander-era Seattle D" },
  { id: "niners89", name: "1989 49ers", position: "DST", team: "SF", careerStart: 1989, careerEnd: 1989, statLine: "Super Bowl XXIV · Lott/Haley 14–2 D" },
  { id: "niners19", name: "2019 49ers", position: "DST", team: "SF", careerStart: 2019, careerEnd: 2019, statLine: "Super Bowl LIV · Bosa/Warner/Sherman D" },
  { id: "bucs79", name: "1979 Buccaneers", position: "DST", team: "TB", careerStart: 1979, careerEnd: 1979, statLine: "NFC title game · Selmon’s first Tampa D" },
  { id: "bucs20", name: "2020 Buccaneers", position: "DST", team: "TB", careerStart: 2020, careerEnd: 2020, statLine: "Super Bowl LV · David/White/Winfield D" },
  { id: "oilers79", name: "1979 Oilers", position: "DST", team: "TEN", careerStart: 1979, careerEnd: 1979, statLine: "AFC title game · Luv Ya Blue Bethea/Bingham D" },
  { id: "titans08", name: "2008 Titans", position: "DST", team: "TEN", careerStart: 2008, careerEnd: 2008, statLine: "13–3 AFC South · Haynesworth/Finnegan D" },
  { id: "washington72", name: "1972 Washington", position: "DST", team: "WAS", careerStart: 1972, careerEnd: 1972, statLine: "Super Bowl VII · Over-the-Hill Gang" },
  { id: "washington82", name: "1982 Washington", position: "DST", team: "WAS", careerStart: 1982, careerEnd: 1982, statLine: "Super Bowl XVII · Hogs-era championship D" },
];

function assignTargets(core, extras) {
  const usedStd = new Set(core.map((player) => player.targetStd));
  const usedPpr = new Set(core.map((player) => player.targetPpr));
  let std = 30;
  let ppr = 45;
  const next = (used, start) => {
    let n = start;
    while (used.has(n)) n += 1;
    used.add(n);
    return n;
  };
  return extras.map((player) => {
    const targetStd = next(usedStd, std);
    const targetPpr = next(usedPpr, ppr);
    std = targetStd + 1;
    ppr = targetPpr + 1;
    return { ...player, targetStd, targetPpr };
  });
}

const DEFENDERS = [...CORE_DEFENDERS, ...assignTargets(CORE_DEFENDERS, FRANCHISE_IDP)];

function insert(list, extras, targetKey, rankKey) {
  const next = [...list];
  const ordered = [...extras].sort((a, b) => a[targetKey] - b[targetKey]);
  for (const extra of ordered) {
    const index = Math.min(Math.max(extra[targetKey] - 1, 0), next.length);
    next.splice(index, 0, extra);
  }
  next.forEach((player, index) => {
    player[rankKey] = index + 1;
  });
  return next;
}

const missing = offense.filter((player) => !STATS[player.id]).map((player) => player.id);
if (missing.length) {
  throw new Error(`Missing stat lines: ${missing.join(", ")}`);
}

const offenseWithStats = offense.map((player) => ({
  ...player,
  statLine: STATS[player.id],
}));
const defenders = DEFENDERS.map(({ targetStd, targetPpr, ...player }) => ({
  ...player,
  targetStd,
  targetPpr,
  standardRank: 0,
  pprRank: 0,
}));

const byStandard = insert(offenseWithStats.sort((a, b) => a.standardRank - b.standardRank), defenders, "targetStd", "standardRank");
const byPpr = insert(
  offenseWithStats.sort((a, b) => a.pprRank - b.pprRank),
  defenders,
  "targetPpr",
  "pprRank",
);

if (byStandard.length !== byPpr.length) {
  throw new Error("Rank lists diverged");
}

const stdSet = new Set(byStandard.map((p) => p.standardRank));
const pprSet = new Set(byPpr.map((p) => p.pprRank));
if (stdSet.size !== byStandard.length || pprSet.size !== byPpr.length) {
  throw new Error("Non-unique ranks after merge");
}

const pool = byStandard.map(({ targetStd, targetPpr, ...player }) => ({
  ...player,
  teams: playerTeamCodes(player),
}));
const out = JSON.stringify(pool, null, 2) + "\n";
const dests = [
  path.join(root, "src/lib/players.json"),
  path.join(root, "standalone/players.json"),
];
for (const dest of dests) {
  fs.writeFileSync(dest, out);
}
console.log(`Wrote ${pool.length} players (${offense.length} offense + ${defenders.length} IDP/DST)`);
